"""Delineate a catchment polygon from one outlet coordinate.

Purpose
-------
Transform one configured outlet point into canonical watershed products
(``outlet.shp``, ``outlet_snap.shp``, ``watershed.tif``, ``watershed.shp``).

Pipeline position
-----------------
Used when ``catch_def='from_outlet_coord'`` in the geographic workflow.

Processing steps
----------------
1. Build a point layer from ``x_outlet`` / ``y_outlet``.
2. Snap the point to the nearest strong-flow cell on accumulation raster.
3. Run watershed delineation from D8 direction raster.
4. Polygonize the resulting watershed raster for downstream GIS/domain usage.

Why this file computes nothing
------------------------------
All four steps belong to :meth:`TerrainEngine.delineate
<hydromodpy.spatial.terrain.TerrainEngine.delineate>`. What stays here is the
one thing the engine has no business knowing: this pipeline publishes its
catchment as ``watershed.tif`` and ``watershed.shp``, flat in a directory that
twenty other artefacts share, and every golden in the tree reads them there.
That shape is passed to the engine as a
:class:`~hydromodpy.spatial.terrain.CatchmentLayout`.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from hydromodpy.core import progress
from hydromodpy.core.exceptions import TerrainProductError
from hydromodpy.core.io.crs import ensure_crs
from hydromodpy.core.logging import get_logger
from hydromodpy.spatial.terrain import (
    OUTLET_LAYER_NAME,
    SNAPPED_OUTLET_LAYER_NAME,
    CatchmentLayout,
    FlowAccumulation,
    Outlet,
)
from hydromodpy.spatial.terrain.whitebox_engine import WhiteboxTerrainEngine

logger = get_logger(__name__)

WATERSHED_TIF_NAME = "watershed.tif"
WATERSHED_SHP_NAME = "watershed.shp"

CATCHMENT_LAYOUT = CatchmentLayout.flat(
    mask_name=WATERSHED_TIF_NAME,
    boundary_name=WATERSHED_SHP_NAME,
)
"""The on-disk shape this pipeline has always published, now declared.

Flat rather than one directory per outlet, because ``GeographicPaths`` names
``watershed.tif`` and ``watershed.shp`` inside ``geographic/`` and moving them
would move every golden that reads them.
"""

OUTLET_ID = "outlet"
"""The name the engine puts in its refusals; a flat layout has no directory."""


@dataclass(frozen=True)
class CatchmentFromPointProducts:
    """Paths to all artifacts generated by outlet-based delineation."""

    outlet_shp: str
    outlet_snap_shp: str
    watershed_tif: str
    watershed_shp: str
    x_outlet_snapped: float | None = None
    """X the delineation actually ran from, after the snap moved the declared point.

    None when the products were not produced by an outlet snap, which is why the
    three snap fields carry a default: not every construction path snaps.
    """

    y_outlet_snapped: float | None = None
    """Y the delineation actually ran from, after the snap moved the declared point."""

    snap_distance_m: float | None = None
    """Distance the snap moved the outlet. The declared coordinate is not the one used."""


def extract_catchment_from_point(
    *,
    x_outlet: float,
    y_outlet: float,
    snap_dist: int,
    accumulation: FlowAccumulation,
    output_dir: str | Path,
    crs_project: str | None = None,
    backend: object | None = None,
) -> CatchmentFromPointProducts:
    """Delineate a catchment polygon from one outlet point.

    Parameters
    ----------
    x_outlet, y_outlet:
        Outlet coordinates in model projected CRS.
    snap_dist:
        Width of the square snap window, in map units. Not a maximum
        displacement: a value equal to one cell size snaps nowhere, and 100 m on
        a 25 m grid can move an outlet 70.7 m diagonally.
    accumulation:
        The regional accumulation to snap against, with the pointer it was
        derived from. Both are the engine's own products.
    output_dir:
        Folder where output files are written.
    crs_project:
        Optional CRS enforced on generated files, on top of the one the engine
        carries from the source DEM.
    backend:
        Optional Whitebox backend for runtime/tests.
    """
    engine = WhiteboxTerrainEngine(backend)
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    with progress.status("Delineating watershed"):
        try:
            (catchment,) = engine.delineate(
                accumulation,
                [Outlet(outlet_id=OUTLET_ID, x=float(x_outlet), y=float(y_outlet))],
                out_dir=out_dir,
                snap_distance_m=float(snap_dist),
                layout=CATCHMENT_LAYOUT,
            )
        except TerrainProductError as exc:
            # The engine knows rasters and windows; only this layer knows which
            # configuration keys the user would have to change. Re-raised as its
            # own class and not as the base one: the breach-then-fill retry of
            # the domain pipeline decides on EmptyCatchmentError, and widening
            # the type here would turn that retry off without a word.
            raise type(exc)(
                f"{exc} Check geographic.x_outlet / geographic.y_outlet, increase "
                "geographic.snap_dist, or verify that the corrected DEM and "
                "flow-accumulation rasters cover the outlet."
            ) from exc

    outlet_shp = out_dir / OUTLET_LAYER_NAME
    outlet_snap_shp = out_dir / SNAPPED_OUTLET_LAYER_NAME
    for path in (outlet_shp, outlet_snap_shp, catchment.mask_path, catchment.boundary_path):
        ensure_crs(path, crs_project)

    # The declared coordinate is what every report shows; say how far the
    # delineation actually started from it, because nothing downstream can tell.
    log = logger.warning if catchment.snap_distance_m > 0.5 * float(snap_dist) else logger.info
    log(
        "Outlet snapped %.1f m (of %d m allowed), from (%.2f, %.2f) to (%.2f, %.2f). "
        "The catchment is delineated from the snapped point.",
        catchment.snap_distance_m,
        int(snap_dist),
        x_outlet,
        y_outlet,
        catchment.snapped_x,
        catchment.snapped_y,
    )

    return CatchmentFromPointProducts(
        outlet_shp=str(outlet_shp),
        outlet_snap_shp=str(outlet_snap_shp),
        watershed_tif=str(catchment.mask_path),
        watershed_shp=str(catchment.boundary_path),
        x_outlet_snapped=catchment.snapped_x,
        y_outlet_snapped=catchment.snapped_y,
        snap_distance_m=catchment.snap_distance_m,
    )
