"""Delineate a catchment polygon from one outlet coordinate.

Purpose
-------
Transform one configured outlet point into canonical watershed products
(``outlet.shp``, ``outlet_snap.shp``, ``watershed.tif``, ``watershed.shp``).

Pipeline position
-----------------
Used when ``catch_def='from_outlet_coord'`` in the geographic workflow.

Processing steps
----------------
1. Build a point layer from ``x_outlet`` / ``y_outlet``.
2. Snap the point to the nearest strong-flow cell on accumulation raster.
3. Run watershed delineation from D8 direction raster.
4. Polygonize the resulting watershed raster for downstream GIS/domain usage.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import geopandas as gpd
import pandas as pd

from hydromodpy.core.backends import WhiteboxBackend, WhiteboxWorkflowsBackend, get_whitebox_backend

from hydromodpy.spatial.geographic.geographic_io import ensure_crs


@dataclass(frozen=True)
class CatchmentFromPointProducts:
    """Paths to all artifacts generated by outlet-based delineation."""

    outlet_shp: str
    outlet_snap_shp: str
    watershed_tif: str
    watershed_shp: str


def extract_catchment_from_point(
    *,
    x_outlet: float,
    y_outlet: float,
    snap_dist: int,
    acc_path: str | Path,
    direc_path: str | Path,
    output_dir: str | Path,
    crs_project: str | None = None,
    acc_data: object | None = None,
    direc_data: object | None = None,
    outlet_name: str = "outlet.shp",
    outlet_snap_name: str = "outlet_snap.shp",
    watershed_tif_name: str = "watershed.tif",
    watershed_shp_name: str = "watershed.shp",
    backend: WhiteboxBackend | None = None,
) -> CatchmentFromPointProducts:
    """Delineate a catchment polygon from one outlet point.

    Parameters
    ----------
    x_outlet, y_outlet:
        Outlet coordinates in model projected CRS.
    snap_dist:
        Max snapping distance used by Whitebox (map units, usually meters).
    acc_path, direc_path:
        D8 accumulation and direction rasters on compatible support.
    output_dir:
        Folder where output files are written.
    crs_project:
        Optional CRS enforced on generated files.
    *_name:
        Filenames used inside ``output_dir``.
    backend:
        Optional Whitebox backend for runtime/tests.
    """
    tool = get_whitebox_backend() if backend is None else backend

    # Prepare deterministic output paths used by the rest of the pipeline.
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    outlet_shp = out_dir / outlet_name
    outlet_snap_shp = out_dir / outlet_snap_name
    watershed_tif = out_dir / watershed_tif_name
    watershed_shp = out_dir / watershed_shp_name

    # Whitebox receives outlets through a point shapefile input.
    df = pd.DataFrame({"x": [float(x_outlet)], "y": [float(y_outlet)]})
    gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df["x"], df["y"]), crs=crs_project)
    gdf.to_file(str(outlet_shp))
    ensure_crs(outlet_shp, crs_project)

    if isinstance(tool, WhiteboxWorkflowsBackend):
        outlet_data = tool.read_vector(str(outlet_shp))
        acc_input = acc_data if acc_data is not None else tool.read_raster(str(acc_path))
        snapped_outlet = tool.snap_pour_points_vector(
            outlet_data,
            acc_input,
            int(snap_dist),
        )
        if tool.vector_record_count(snapped_outlet) == 0:
            raise ValueError(
                "Outlet snapping produced no feature. Check geographic.x_outlet / "
                "geographic.y_outlet, increase geographic.snap_dist, or verify "
                "that the corrected DEM and flow-accumulation rasters cover the outlet."
            )
        tool.write_vector(snapped_outlet, str(outlet_snap_shp))
        ensure_crs(outlet_snap_shp, crs_project)

        direc_input = direc_data if direc_data is not None else tool.read_raster(str(direc_path))
        watershed_data = tool.watershed_raster(
            direc_input,
            snapped_outlet,
            esri_pntr=False,
        )
        tool.write_raster(watershed_data, str(watershed_tif))
        ensure_crs(watershed_tif, crs_project)

        # Polygon output is the canonical boundary format used downstream.
        watershed_vector = tool.raster_to_vector_polygons_raster(watershed_data)
        if tool.vector_record_count(watershed_vector) == 0:
            raise ValueError(
                "Watershed delineation produced an empty polygon. Check outlet placement, "
                "DEM conditioning, and snap distance before rerunning the geographic pipeline."
            )
        tool.write_vector(watershed_vector, str(watershed_shp))
        ensure_crs(watershed_shp, crs_project)
    else:
        # Snap stabilizes delineation when outlet is not exactly on a flow cell.
        tool.snap_pour_points(
            str(outlet_shp),
            str(acc_path),
            str(outlet_snap_shp),
            int(snap_dist),
        )
        ensure_crs(outlet_snap_shp, crs_project)

        # D8 watershed delineation from snapped outlet.
        tool.watershed(
            str(direc_path),
            str(outlet_snap_shp),
            str(watershed_tif),
            esri_pntr=False,
        )
        ensure_crs(watershed_tif, crs_project)

        # Polygon output is the canonical boundary format used downstream.
        tool.raster_to_vector_polygons(str(watershed_tif), str(watershed_shp))
        ensure_crs(watershed_shp, crs_project)

    return CatchmentFromPointProducts(
        outlet_shp=str(outlet_shp),
        outlet_snap_shp=str(outlet_snap_shp),
        watershed_tif=str(watershed_tif),
        watershed_shp=str(watershed_shp),
    )
