[[simulation.process]]
solvers = ["modflow6"]

[modflow6.runtime]
mf_verbose = false
mf6_ims_complexity = "COMPLEX"

[modflow6.process_specific]
vka = 1.0

[modflow6.sgrid.planar]
mode = "resample_to_shape"
nx = 40
ny = 24
resampling = "nearest"

[modflow6.sgrid.vertical]
nlay = 1

[modflow6.tgrid]
firstpersteady = true
