# ----------------------------------------------------------------------
# Geographic-only case extracted from examples_legacy/example12/config.toml
# ----------------------------------------------------------------------

[workspace]
catch_name = "example12_geographic_case"
out_dir_path = "../../../examples/results"
data_path = "../../../examples_legacy/example12/data"

[geographic]
catch_def = "from_outlet_coord"
dem_init_path = "../../../data/Brittany/dem/regional dem.tif"
x_outlet = 265611.933
y_outlet = 6784182.776
snap_dist = "50 m"
buff_area = "20%"
crs_project = "EPSG:2154"
dem_correc_type = "breach"
