"""Mesh helper package shared by solver-side workflows."""

from hydromodpy.solver.utils.mesh.cartesian_grid.sgrid_mesh_adapter import (
    build_field_mesh_from_sgrid,
    extract_structured_vertices,
)
from hydromodpy.solver.utils.mesh.gmsh_grid import (
    ExtrudedFieldParamDiscretizationResult,
    ExtrudedPrismMesh3D,
    ExtrudedPrismMeshData,
    ExtrudedPrismMeshWithValues,
    GmshMeshData,
    GmshPlanarMesh2D,
    attach_extruded_values,
    build_layer_maps_figure,
    build_vertical_profiles_figure,
    discretize_fieldparam_on_extruded_mesh,
    load_extruded_mesh,
    load_extruded_mesh_values,
    load_planar_mesh,
    read_extruded_prism_mesh,
    read_gmsh_2d_mesh,
    save_extruded_mesh,
    save_extruded_mesh_values,
    save_extruded_values_npy,
    save_extruded_values_summary,
    save_planar_mesh,
    write_extruded_prism_mesh,
    write_gmsh_2d_mesh,
)

__all__ = [
    "build_field_mesh_from_sgrid",
    "extract_structured_vertices",
    "ExtrudedFieldParamDiscretizationResult",
    "ExtrudedPrismMesh3D",
    "ExtrudedPrismMeshData",
    "ExtrudedPrismMeshWithValues",
    "GmshMeshData",
    "GmshPlanarMesh2D",
    "attach_extruded_values",
    "build_layer_maps_figure",
    "build_vertical_profiles_figure",
    "discretize_fieldparam_on_extruded_mesh",
    "load_extruded_mesh",
    "load_extruded_mesh_values",
    "load_planar_mesh",
    "read_extruded_prism_mesh",
    "read_gmsh_2d_mesh",
    "save_extruded_mesh",
    "save_extruded_mesh_values",
    "save_extruded_values_npy",
    "save_extruded_values_summary",
    "save_planar_mesh",
    "write_extruded_prism_mesh",
    "write_gmsh_2d_mesh",
]
