"""Minimal, valid example files for each accepted custom input format.

Generated by :mod:`hydromodpy.data.scaffold` during ``hmp workspace init``.
Every file carries the ``EXAMPLE`` id token in its name so the loaders and
``auto_scan`` skip it (see
:func:`hydromodpy.data.common.io_helpers.is_scaffold_example`): these are format
templates, never ingested as real data. The user replaces them with their own
files following the same naming convention.

Geospatial libraries (geopandas, rasterio, xarray) are imported lazily inside
the writers so importing this module stays cheap.
"""

from __future__ import annotations

from pathlib import Path

# Small synthetic footprint in Lambert-93 (EPSG:2154), Brittany-like.
_CRS = "EPSG:2154"
_LEFT = 350000.0
_TOP = 6780500.0
_CELL = 100.0
_N = 5
_BOTTOM = _TOP - _CELL * _N  # 6780000.0
_RIGHT = _LEFT + _CELL * _N  # 350500.0
_NODATA = -9999.0


def write_variable_examples(
    var_dir: Path,
    *,
    category: str,
    file_prefix: str,
    unit: str,
) -> list[Path]:
    """Write one example file per accepted input format for a variable.

    ``category`` is one of ``point``, ``grid``, ``dem``, ``geology``,
    ``hydrography``. Returns the list of written (or already present) paths.
    """
    var_dir.mkdir(parents=True, exist_ok=True)
    if category == "point":
        return _point_examples(var_dir, file_prefix, unit)
    if category == "grid":
        return _grid_examples(var_dir, file_prefix, unit)
    if category == "dem":
        return _dem_examples(var_dir, file_prefix, unit)
    if category == "geology":
        return _geology_examples(var_dir, file_prefix)
    if category == "hydrography":
        return _hydrography_examples(var_dir, file_prefix)
    if category == "table":
        return _table_examples(var_dir, file_prefix)
    return []


def _table_examples(var_dir: Path, prefix: str) -> list[Path]:
    path = var_dir / f"{prefix}_custom_EXAMPLE.csv"
    if not path.exists():
        path.write_text(
            "stage,volume,sarea\n85.0,0.0,0.0\n87.0,2.0e5,1.0e5\n90.0,1.2e6,4.0e5\n",
            encoding="utf-8",
        )
    return [path]


# ---------------------------------------------------------------------------
# Per-category dispatch
# ---------------------------------------------------------------------------


def _point_examples(var_dir: Path, prefix: str, unit: str) -> list[Path]:
    return [
        _write_loc_csv(var_dir / f"{prefix}_custom_LOC.csv"),
        _write_chronicle_csv(
            var_dir / f"{prefix}_custom_EXAMPLE_20000101_20000131_D.csv", unit=unit
        ),
    ]


def _grid_examples(var_dir: Path, prefix: str, unit: str) -> list[Path]:
    out = _point_examples(var_dir, prefix, unit)
    out.append(_write_netcdf(var_dir / f"{prefix}_custom_EXAMPLE.nc", var=prefix, unit=unit))
    out.append(
        _write_geotiff(
            var_dir / f"{prefix}_custom_EXAMPLE.tif", values=_ramp_grid(), dtype="float32"
        )
    )
    return out


def _dem_examples(var_dir: Path, prefix: str, unit: str) -> list[Path]:
    return [
        _write_geotiff(
            var_dir / f"{prefix}_custom_EXAMPLE.tif", values=_elevation_grid(), dtype="float32"
        ),
        _write_asc(var_dir / f"{prefix}_custom_EXAMPLE.asc", values=_elevation_grid()),
        _write_netcdf(var_dir / f"{prefix}_custom_EXAMPLE.nc", var="elevation", unit=unit),
    ]


def _geology_examples(var_dir: Path, prefix: str) -> list[Path]:
    gdf = _polygon_gdf()
    return [
        _write_vector(var_dir / f"{prefix}_custom_EXAMPLE.gpkg", gdf, driver="GPKG"),
        _write_vector(var_dir / f"{prefix}_custom_EXAMPLE.shp", gdf, driver="ESRI Shapefile"),
        _write_vector(var_dir / f"{prefix}_custom_EXAMPLE.geojson", gdf, driver="GeoJSON"),
        _write_geotiff(
            var_dir / f"{prefix}_custom_EXAMPLE.tif",
            values=_class_grid(),
            dtype="int32",
            nodata=0,
        ),
        _write_geology_csv(var_dir / f"{prefix}_custom_EXAMPLE.csv"),
    ]


def _hydrography_examples(var_dir: Path, prefix: str) -> list[Path]:
    gdf = _line_gdf()
    return [
        _write_vector(var_dir / f"{prefix}_custom_EXAMPLE.gpkg", gdf, driver="GPKG"),
        _write_vector(var_dir / f"{prefix}_custom_EXAMPLE.shp", gdf, driver="ESRI Shapefile"),
        _write_vector(var_dir / f"{prefix}_custom_EXAMPLE.geojson", gdf, driver="GeoJSON"),
        _write_geotiff(
            var_dir / f"{prefix}_custom_EXAMPLE.tif", values=_stream_grid(), dtype="float32"
        ),
    ]


# ---------------------------------------------------------------------------
# Tabular writers
# ---------------------------------------------------------------------------


def _write_loc_csv(path: Path) -> Path:
    """Header-only station-location template (kept inert until the user fills it)."""
    if not path.exists():
        path.write_text("id,x,y,crs,unit\n", encoding="utf-8")
    return path


def _write_chronicle_csv(path: Path, *, unit: str, days: int = 31) -> Path:
    if path.exists():
        return path
    import pandas as pd

    index = pd.date_range("2000-01-01", periods=days, freq="D")
    frame = pd.DataFrame(
        {
            "datetime": index.strftime("%Y-%m-%d"),
            "value": [round(1.0 + 0.1 * i, 3) for i in range(days)],
        }
    )
    frame.to_csv(path, index=False)
    return path


def _write_geology_csv(path: Path) -> Path:
    """Point table (x, y, geology_code) for Voronoi interpolation."""
    if path.exists():
        return path
    import pandas as pd

    rows = [
        (_LEFT + 120.0, _BOTTOM + 120.0, "GRANITE"),
        (_RIGHT - 120.0, _TOP - 120.0, "SCHIST"),
        ((_LEFT + _RIGHT) / 2, (_TOP + _BOTTOM) / 2, "ALLUVIUM"),
    ]
    pd.DataFrame(rows, columns=["x", "y", "geology_code"]).to_csv(path, index=False)
    return path


# ---------------------------------------------------------------------------
# Raster writers
# ---------------------------------------------------------------------------


def _write_geotiff(path: Path, *, values, dtype: str, nodata: float | int = _NODATA) -> Path:
    if path.exists():
        return path
    import numpy as np
    import rasterio
    from rasterio.transform import from_origin

    array = np.asarray(values, dtype=dtype)
    transform = from_origin(_LEFT, _TOP, _CELL, _CELL)
    with rasterio.open(
        path,
        "w",
        driver="GTiff",
        height=array.shape[0],
        width=array.shape[1],
        count=1,
        dtype=array.dtype,
        crs=_CRS,
        transform=transform,
        nodata=nodata,
    ) as dst:
        dst.write(array, 1)
    return path


def _write_asc(path: Path, *, values) -> Path:
    if path.exists():
        return path
    import numpy as np
    import rasterio
    from rasterio.transform import from_origin

    array = np.asarray(values, dtype="float32")
    transform = from_origin(_LEFT, _TOP, _CELL, _CELL)
    with rasterio.open(
        path,
        "w",
        driver="AAIGrid",
        height=array.shape[0],
        width=array.shape[1],
        count=1,
        dtype="float32",
        crs=_CRS,
        transform=transform,
        nodata=_NODATA,
    ) as dst:
        dst.write(array, 1)
    return path


def _write_netcdf(path: Path, *, var: str, unit: str) -> Path:
    """Small (time, y, x) grid with CRS metadata and a fill value."""
    if path.exists():
        return path
    import numpy as np
    import pandas as pd
    import xarray as xr

    xs = _LEFT + _CELL * (np.arange(_N) + 0.5)
    ys = _BOTTOM + _CELL * (np.arange(_N) + 0.5)
    times = pd.date_range("2000-01-01", periods=3, freq="D")
    data = (np.arange(3 * _N * _N, dtype="float32").reshape(3, _N, _N) % 10) + 1.0
    dataset = xr.Dataset(
        {var: (("time", "y", "x"), data)},
        coords={"time": times, "x": xs, "y": ys},
    )
    dataset[var].attrs["units"] = unit
    dataset[var].attrs["nodata"] = _NODATA
    dataset.attrs["crs"] = _CRS
    dataset.to_netcdf(path, encoding={var: {"_FillValue": _NODATA}})
    return path


# ---------------------------------------------------------------------------
# Vector writers
# ---------------------------------------------------------------------------


def _write_vector(path: Path, gdf, *, driver: str) -> Path:
    if path.exists():
        return path
    # GeoJSON is defined in WGS84; reproject so the file is spec-compliant.
    out = gdf.to_crs(4326) if driver == "GeoJSON" else gdf
    out.to_file(path, driver=driver)
    return path


def _polygon_gdf():
    import geopandas as gpd
    from shapely.geometry import box

    mid = _LEFT + _CELL * _N / 2
    return gpd.GeoDataFrame(
        {"CODE": ["GRANITE", "SCHIST"]},
        geometry=[box(_LEFT, _BOTTOM, mid, _TOP), box(mid, _BOTTOM, _RIGHT, _TOP)],
        crs=_CRS,
    )


def _line_gdf():
    import geopandas as gpd
    from shapely.geometry import LineString

    return gpd.GeoDataFrame(
        {"name": ["stream_a", "stream_b"], "strahler": [1, 2]},
        geometry=[
            LineString([(_LEFT + 50, _BOTTOM + 50), (_RIGHT - 50, _TOP - 50)]),
            LineString([(_LEFT + 50, _TOP - 50), (_RIGHT - 50, _BOTTOM + 50)]),
        ],
        crs=_CRS,
    )


# ---------------------------------------------------------------------------
# Grid value helpers
# ---------------------------------------------------------------------------


def _ramp_grid():
    import numpy as np

    return (np.arange(_N * _N, dtype="float32").reshape(_N, _N) % 10) + 1.0


def _elevation_grid():
    import numpy as np

    rows = np.arange(_N, dtype="float32")[:, None]
    cols = np.arange(_N, dtype="float32")[None, :]
    return 100.0 + 2.0 * rows + cols


def _class_grid():
    return [
        [1, 1, 1, 2, 2],
        [1, 1, 2, 2, 2],
        [1, 2, 2, 2, 3],
        [2, 2, 2, 3, 3],
        [2, 2, 3, 3, 3],
    ]


def _stream_grid():
    return [
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
    ]
