base_config = "config_headwater_100km2.toml"

[workspace]
project_root = "~/HydroModPy/mesh_gallery_headwater_100km2_outlet_27_geology_rivers_min200"

[geographic]
dem_init_path = "../../../examples/data/dem/DEM_armorican_massif.tif"

[mesh_catchment_batch]
selection_mode = "selected"
selected_outlet_ids = [27]

[mesh_catchment.geology.source]
path = "../../../examples/data/geology/GEO1M.shp"
reference_raster_path = "../../../examples/data/dem/DEM_armorican_massif.tif"

[mesh_catchment.hydraulic_properties.conductivity]
values_csv_file = "../../../examples/data/geology/geology_K_dummy_demo.csv"

[mesh_catchment.zone_meshing]
min_size = 200.0
interface_size = 200.0
