workflow = "simulation"

[[simulation.process]]
solvers = ["modflow6"]

[modflow6.runtime]
mf6_ims_complexity = "SIMPLE"
mf_verbose = false

[modflow6.process_specific]
vka = 1.0

[modflow6.sgrid.vertical]
nlay = 1

[mesh_input]
mesh_path = "../../../shared/mesh_bundles/sloping_substratum_irregular_tri_400x50/mesh_2d.msh"
bundle_dir = "../../../shared/mesh_bundles/sloping_substratum_irregular_tri_400x50"
