"""Render the figure-catalog inventory consumed by ``user_guide/figures.rst``.

The output is one RST fragment grouped by :data:`hydromodpy.display.figure.FigureKind`.
Each row carries the registered figure name, its display title, and the
result fields or tables the figure reads at render time.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from hydromodpy.display import list_figures
from hydromodpy.display.figure import FigureSpec

KIND_LABELS: dict[str, str] = {
    "spatial": "Spatial maps",
    "section": "Cross-sections",
    "timeseries": "Time series",
    "balance": "Budgets and balances",
    "particles": "Particle tracking",
    "comparison": "Comparisons and overlays",
    "table": "Hydrochemistry diagrams",
    "animation": "Animations",
}

KIND_BLURBS: dict[str, str] = {
    "spatial": "Mesh- or raster-backed scalar maps of one persisted field.",
    "section": "Vertical or transverse cuts through a persisted field.",
    "timeseries": "Chronicles read from the catalog ``timeseries`` table.",
    "balance": "Integrated budget or mass-balance summaries.",
    "particles": "Pathline or particle-track outputs.",
    "comparison": (
        "Multi-panel views combining one or several runs, observed data, or calibration traces."
    ),
    "table": "Tabular hydrochemistry diagrams built from water-quality samples.",
    "animation": "Animated views of one persisted field over time.",
}

_HEADER = (
    ".. AUTO-GENERATED by ``python -m tools.doc_figures``. Do not edit by hand.\n"
    ".. The Sphinx ``conf.py`` regenerates this file on every build through\n"
    ".. the ``builder-inited`` hook.\n"
    "\n"
)


def _required_summary(spec: FigureSpec) -> str:
    """Return a human-readable summary of the inputs the figure needs."""
    parts: list[str] = []
    if spec.required_fields:
        parts.append("fields " + ", ".join(f"``{name}``" for name in spec.required_fields))
    if spec.required_tables:
        parts.append("tables " + ", ".join(f"``{name}``" for name in spec.required_tables))
    return "; ".join(parts) if parts else "(no fixed input)"


def _format_kind_section(kind: str, label: str, specs: list[FigureSpec]) -> list[str]:
    blurb = KIND_BLURBS.get(kind, "")
    lines: list[str] = [
        label,
        "~" * len(label),
        "",
    ]
    if blurb:
        lines.append(blurb)
        lines.append("")
    lines.extend(
        [
            ".. list-table::",
            "   :header-rows: 1",
            "   :widths: 32 38 30",
            "",
            "   * - Figure name",
            "     - Title",
            "     - Required inputs",
        ]
    )
    for spec in specs:
        lines.append(f"   * - ``{spec.name}``")
        lines.append(f"     - {spec.title}")
        lines.append(f"     - {_required_summary(spec)}")
    lines.append("")
    return lines


def _build_body(specs: list[FigureSpec]) -> str:
    grouped: dict[str, list[FigureSpec]] = defaultdict(list)
    for spec in specs:
        grouped[spec.kind].append(spec)

    body_lines: list[str] = []
    for kind, label in KIND_LABELS.items():
        kind_specs = grouped.pop(kind, [])
        if not kind_specs:
            continue
        body_lines.extend(_format_kind_section(kind, label, kind_specs))

    # Any unknown kind that escapes KIND_LABELS is still rendered so the
    # catalog stays exhaustive even if a new kind lands without a label.
    for kind in sorted(grouped):
        body_lines.extend(_format_kind_section(kind, kind.capitalize(), grouped[kind]))

    return "\n".join(body_lines)


def _output_path() -> Path:
    return (
        Path(__file__).resolve().parents[2]
        / "docs"
        / "source"
        / "user_guide"
        / "figures_inventory.partial.rst"
    )


def generate() -> Path:
    """Write the partial RST file and return its path."""
    specs = list_figures()
    output_file = _output_path()
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(_HEADER + _build_body(specs), encoding="utf-8")
    return output_file
