name: pyhelp_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - matplotlib-inline
  - xarray
  - netcdf4
  - h5netcdf
  - cftime
  - geopandas
  - shapely
  - pyproj
  - fiona
  - rasterio
