"""JSON Schema export for HydroModPy Pydantic configuration models.

Exports the JSON Schema describing ``HydroModPyConfig`` (or any sub-model)
so that IDEs (VS Code + ``even-better-toml``, JSON-Schema-aware UIs) can
provide autocompletion, validation, and documentation for HydroModPy TOML
configurations.

The exporter preserves the rich ``json_schema_extra`` annotations attached
to fields (``widget_type``, ``unit``, ``display_name_fr``, ``help_text_fr``,
``display_min``, ``display_max``) which a front-end (Streamlit, React, ...)
can consume to render tailored widgets.

Usage
-----
Python API::

    from hydromodpy.core.config_kit.schema_export import export_schema
    from hydromodpy.physics.flow.flow_config import FlowConfig

    schema = export_schema(FlowConfig)
    # full root schema:
    schema = export_schema()

    # by section name (e.g. "flow", "workspace", ...)
    schema = export_schema(section="flow")

CLI::

    hmp config schema                     # full root schema to stdout
    hmp config schema --section flow      # one section
    hmp config schema --out schema.json   # write to file
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from hydromodpy.core.config_kit.registry import root_sections as _root_sections
from hydromodpy.core.config_kit.root_config_protocol import get_root_config_provider


def _ensure_root_sections() -> dict[str, type]:
    """Return the map of root-level TOML sections to Pydantic model classes."""
    return _root_sections()


def export_schema(
    model_cls: type | None = None,
    *,
    section: str | None = None,
) -> dict[str, Any]:
    """Export a JSON Schema dict for a HydroModPy configuration model.

    Parameters
    ----------
    model_cls
        A Pydantic ``BaseModel`` subclass. If ``None``, the root
        ``HydroModPyConfig`` model is used.
    section
        Name of a root TOML section (see :func:`_ensure_root_sections`). When
        given, overrides ``model_cls``.

    Returns
    -------
    dict
        JSON Schema document (draft 2020-12 compatible, as emitted by
        Pydantic v2).
    """
    if section is not None:
        sections = _ensure_root_sections()
        if section not in sections:
            allowed = ", ".join(sorted(sections))
            raise ValueError(f"unknown config section {section!r} (allowed: {allowed})")
        model_cls = sections[section]

    if model_cls is None:
        model_cls = get_root_config_provider().root_model()

    schema = model_cls.model_json_schema()
    # Attach a meta marker so downstream tools can identify the producer.
    schema.setdefault("$comment", "Generated by hydromodpy.core.config_kit.schema_export")
    return schema


def write_schema(
    path: str | Path,
    *,
    model_cls: type | None = None,
    section: str | None = None,
    indent: int = 2,
) -> Path:
    """Serialize an exported schema to a JSON file.

    Returns the resolved :class:`Path` of the written file.
    """
    schema = export_schema(model_cls, section=section)
    out_path = Path(path).expanduser().resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(schema, indent=indent, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return out_path


__all__ = ["export_schema", "write_schema"]
