[[simulation.process]]
solvers = ["modflow6"]

[modflow6.runtime]
mf_verbose = false
mf6_ims_complexity = "COMPLEX"

[modflow6.process_specific]
vka = 1.0

[modflow6.sgrid.vertical]
nlay = 1

[mesh_input]
mesh_path = "../../../shared/mesh_bundles/linearized_unconfined_hillslope_drainage_irregular_tri_100x10/mesh_2d.msh"
bundle_dir = "../../../shared/mesh_bundles/linearized_unconfined_hillslope_drainage_irregular_tri_100x10"
