# Kregional environment file for conda users
# Usage:
#     conda env create -f environment.yml
#     conda activate hydromodpy

name: Kregional
channels:
    - conda-forge
    - defaults
dependencies:
    # Obvious
    - python=3.8.10
    - ipykernel
    - pip
    - pip:
        - colormap #pip install easydev may be necessary

    # Main processing libraries
    - numpy
    
    # Data reading/writing and conversion
    - pandas
    
    # Post-processing
    - matplotlib
    - matplotlib-scalebar

    # Viewing notebooks
    - jupyter
    - jupyterlab
    - spyder
    
    