# ----------------------------------------------------------------------
# Reference geographic multi-case configuration.
# ----------------------------------------------------------------------

[workspace]
project_root = "."

[geographic]
catch_def = "from_outlet_coord"
dem_init_path = "../../../../data/Brittany/dem/regional dem.tif"
x_outlet = 265611.933
y_outlet = 6784182.776
snap_dist = 50
buff_area = 20.0
crs_project = "EPSG:2154"
dem_correc_type = "breach"
