base_config = "/mnt/c/codes/HydroModPy-GH/examples/projects/launcher_simulation/run_headwater_100km2_outlet_2_boussinesq_petsc_transient_cycling_recharge_heterogeneous.toml"

[workspace]
project_root = "/mnt/c/codes/HydroModPy-GH/reporting/boussinesq_figures_2026-04-12/cycling_heterogeneous_petsc_mixed"

[geographic]
dem_init_path = "/mnt/c/codes/HydroModPy-GH/examples/data/dem/DEM_armorican_massif.tif"

[mesh_input]
mesh_path = "/mnt/c/codes/HydroModPy-GH/examples/mesh_gallery/100km2/mesh_headwater_100km2_outlet_2_geology_rivers_buffer30/bundle/mesh_2d.msh"
bundle_dir = "/mnt/c/codes/HydroModPy-GH/examples/mesh_gallery/100km2/mesh_headwater_100km2_outlet_2_geology_rivers_buffer30/bundle"

[display]
show = false
save = true
