"""Tests for :mod:`hydromodpy.core.toml_io.io` and
:meth:`HydroModelBase.to_toml`.

Covers profile filtering (``user`` emits fewer fields than ``expert``) and
a round-trip invariant on :class:`TimeseriesVariableConfig`.
"""

from __future__ import annotations

import tomllib
from pathlib import Path
from typing import get_args, get_origin

import pytest
from pydantic import BaseModel

from hydromodpy.config import HydroModPyConfig
from hydromodpy.core.config_kit.introspect import extract_profile
from hydromodpy.core.config_kit.profile import Profile
from hydromodpy.core.toml_io.io import dump_toml_with_comments
from hydromodpy.data.variables.timeseries_variable_config import (
    TimeseriesVariableConfig,
)


def _load(path: Path) -> dict:
    with path.open("rb") as fh:
        return tomllib.load(fh)


def _unwrap_model(annotation: object) -> type[BaseModel] | None:
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation
    for arg in get_args(annotation):
        nested = _unwrap_model(arg)
        if nested is not None:
            return nested
    return None


def _visible_paths(model_cls: type[BaseModel], threshold: Profile, prefix: str = "") -> set[str]:
    paths: set[str] = set()
    for name, field_info in model_cls.model_fields.items():
        profile = extract_profile(field_info)
        full_path = f"{prefix}.{name}" if prefix else name
        if profile <= threshold:
            paths.add(full_path)
        nested = _unwrap_model(field_info.annotation)
        if nested is not None:
            paths.update(_visible_paths(nested, threshold, full_path))
    return paths


def _profile_paths(profile: Profile) -> set[str]:
    return _visible_paths(HydroModPyConfig, profile)


def test_to_toml_user_profile_omits_dev_fields(tmp_path: Path) -> None:
    cfg = TimeseriesVariableConfig(
        date_start="2020-01-01",
        date_end="2020-12-31",
        station_ids=["A1"],
    )
    out = cfg.to_toml(tmp_path / "user.toml", profile="user")
    payload = _load(out)
    assert "date_start" in payload
    assert "station_ids" in payload
    # Dev-level CSV columns must not leak into the user-profile dump.
    for dev_field in ("col_id", "col_datetime", "default_crs", "force_refresh"):
        assert dev_field not in payload, f"{dev_field!r} leaked into user profile"


def test_to_toml_expert_profile_dumps_every_field(tmp_path: Path) -> None:
    cfg = TimeseriesVariableConfig(
        date_start="2020-01-01",
        date_end="2020-12-31",
        station_ids=["A1"],
        extent="watershed",
    )
    out = cfg.to_toml(tmp_path / "expert.toml", profile="expert")
    payload = _load(out)
    for every_field in (
        "date_start",
        "date_end",
        "station_ids",
        "extent",
        "col_id",
        "col_x",
        "col_y",
        "col_crs",
        "col_datetime",
        "col_value",
        "default_crs",
        "force_refresh",
    ):
        assert every_field in payload


def test_to_toml_rejects_unknown_profile(tmp_path: Path) -> None:
    cfg = TimeseriesVariableConfig(date_start="2020-01-01", date_end="2020-12-31")
    with pytest.raises(ValueError):
        cfg.to_toml(tmp_path / "out.toml", profile="superexpert")


def test_to_toml_roundtrip_preserves_scalar_fields(tmp_path: Path) -> None:
    cfg = TimeseriesVariableConfig(
        date_start="2020-01-01",
        date_end="2020-12-31",
        station_ids=["A1", "B2"],
        force_refresh=True,
        col_datetime="time",
    )
    out = cfg.to_toml(tmp_path / "rt.toml", profile="expert")
    payload = _load(out)
    rebuilt = TimeseriesVariableConfig.model_validate(payload)
    assert rebuilt.date_start == cfg.date_start
    assert rebuilt.date_end == cfg.date_end
    assert rebuilt.station_ids == cfg.station_ids
    assert rebuilt.force_refresh is True
    assert rebuilt.col_datetime == "time"


def test_dump_toml_with_comments_helper(tmp_path: Path) -> None:
    cfg = TimeseriesVariableConfig(date_start="2020-01-01", date_end="2020-12-31")
    out = dump_toml_with_comments(cfg, tmp_path / "alt.toml", profile="dev")
    text = out.read_text()
    assert "Generated by hydromodpy.core.toml_io.io" in text
    assert "profile = 'dev'" in text


def test_profile_visibility_is_monotonic_user_dev_expert() -> None:
    user_paths = _profile_paths(Profile.USER)
    dev_paths = _profile_paths(Profile.DEV)
    expert_paths = _profile_paths(Profile.EXPERT)

    assert user_paths < dev_paths
    assert dev_paths < expert_paths

    expert_only = expert_paths - dev_paths
    assert expert_only
    assert user_paths.isdisjoint(expert_only)


def test_json_schema_exports_examples_metadata() -> None:
    schema = HydroModPyConfig.model_json_schema()

    assert schema["properties"]["workflow"]["examples"] == [{"mode": "simulation"}]
    assert schema["$defs"]["FlowConfig"]["properties"]["param_list"]["examples"] == [
        ["K", "Sy", "Ss"]
    ]
    assert schema["$defs"]["SimulationConfig"]["properties"]["run_id"]["examples"] == ["steady_nwt"]
