"""Extract catchment geometry from one outlet point and D8 flow rasters.

Responsibilities:
- write outlet point shapefile,
- snap outlet to high-accumulation cell,
- delineate watershed raster,
- convert watershed raster to polygon.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import geopandas as gpd
import pandas as pd
import whitebox

from hydromodpy.geographic.geographic_io import ensure_crs

wbt = whitebox.WhiteboxTools()
wbt.verbose = False


@dataclass(frozen=True)
class CatchmentFromPointProducts:
    """Artifacts generated by outlet-based catchment extraction."""

    outlet_shp: str
    outlet_snap_shp: str
    watershed_tif: str
    watershed_shp: str


def extract_catchment_from_point(
    *,
    x_outlet: float,
    y_outlet: float,
    snap_dist: int,
    acc_path: str | Path,
    direc_path: str | Path,
    output_dir: str | Path,
    crs_project: str | None = None,
    outlet_name: str = "outlet.shp",
    outlet_snap_name: str = "outlet_snap.shp",
    watershed_tif_name: str = "watershed.tif",
    watershed_shp_name: str = "watershed.shp",
) -> CatchmentFromPointProducts:
    """
    Build one catchment polygon from an outlet point.

    This is the outlet-based delineation logic previously embedded in
    ``Geographic._build_watershed_from_outlet``.
    """
    # Step 1 - Prepare output folder and canonical output file names.
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    outlet_shp = out_dir / outlet_name
    outlet_snap_shp = out_dir / outlet_snap_name
    watershed_tif = out_dir / watershed_tif_name
    watershed_shp = out_dir / watershed_shp_name

    # Step 2 - Write outlet point as vector input for WhiteboxTools.
    df = pd.DataFrame({"x": [float(x_outlet)], "y": [float(y_outlet)]})
    gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df["x"], df["y"]), crs=crs_project)
    gdf.to_file(str(outlet_shp))
    ensure_crs(outlet_shp, crs_project)

    # Step 3 - Snap outlet to flow accumulation support.
    wbt.snap_pour_points(
        str(outlet_shp),
        str(acc_path),
        str(outlet_snap_shp),
        int(snap_dist),
    )
    ensure_crs(outlet_snap_shp, crs_project)

    # Step 4 - Delineate watershed from D8 flow direction + snapped outlet.
    wbt.watershed(
        str(direc_path),
        str(outlet_snap_shp),
        str(watershed_tif),
        esri_pntr=False,
    )
    ensure_crs(watershed_tif, crs_project)

    # Step 5 - Convert watershed raster to polygon for downstream GIS workflow.
    wbt.raster_to_vector_polygons(str(watershed_tif), str(watershed_shp))
    ensure_crs(watershed_shp, crs_project)

    return CatchmentFromPointProducts(
        outlet_shp=str(outlet_shp),
        outlet_snap_shp=str(outlet_snap_shp),
        watershed_tif=str(watershed_tif),
        watershed_shp=str(watershed_shp),
    )
