
[workflow]
mode = "simulation"

[[simulation.process]]
solvers = ["modflow_nwt"]

[modflownwt.sgrid.planar]
mode = "resample_to_shape"
nx = 40
ny = 3
resampling = "nearest"

[modflownwt.sgrid.vertical]
nlay = 1

[flow.ic]
type = "custom"
value = "50.1 m"
