#PyHELP preprocessing libraries
---
name: pyhelp_env
channels:
  - conda-forge

dependencies:
  - python=3.8
  - pip

  # Dataframe
  - numpy
  - pandas
s
  # NetCDF processing
  - xarray
  - netcdf4
  - h5netcdf
  - cftime

  # SIG
  - geopandas
  - shapely
  - pyproj
  - fiona
  - rasterio

