base_config = "base_nancon_physics.toml"

[workflow]
mode = "simulation"

[workspace]
project_root = "outputs/nancon_network_physical_benchmark/workspaces/mf6_disv_drain_high"
root = "outputs/nancon_network_physical_benchmark/workspaces/mf6_disv_drain_high"

[simulation]
name = "nancon_network_physical_benchmark__mf6_disv_drain_high"
run_id = "nancon_network_physical_benchmark__mf6_disv_drain_high"
description = "MODFLOW 6 DISV Nancon benchmark with high top drainage conductance."
if_exists = "replace"

[mesh_input]
bundle_dir = "../09_comparison_workflow/outputs/nancon_transient_seasonal_hydrography/workspace_mf6/mesh/mesh_catchment_bundle"

[flow.bc.cauchy.drainage]
value = 1.0e-3

[modflow6.runtime]
mf6_ims_complexity = "COMPLEX"
mf6_outer_dvclose = 0.0001
mf6_inner_dvclose = 0.0001
mf6_outer_maximum = 1000
mf6_inner_maximum = 1000
mf6_enable_rewet = false
mf6_newton = false
mf6_newton_under_relaxation = true
mf_verbose = false

[modflow6.process_specific]
vka = 1.0

[modflow6.sgrid.vertical]
nlay = 1

[modflow6.tgrid]
firstpersteady = false
