"""The example catalog that ships inside the wheel.

``catalog.toml`` sits next to this module, so ``hmp example list`` answers with
no network and cannot promise what the installed version does not know about.
One entry per example; every file it needs is listed with its size and its
sha256, which is also the key it is cached under.

The catalog is generated, never hand-edited: see :mod:`hydromodpy.examples.generate`
and ``hmp dev examples manifest``.
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass
from pathlib import Path

CATALOG_FILENAME = "catalog.toml"
SCHEMA_VERSION = 1

_HEADER = """\
# HydroModPy example catalog -- GENERATED FILE, do not edit by hand.
#
# Regenerate with `hmp dev examples manifest`. A unit test compares the
# regenerated bytes against this file, so a drift fails the suite instead of
# shipping a catalog that no longer matches the repository.
#
# `sha256` is both the integrity check and the cache key: blobs live under
# <cache>/examples/blobs/<sha256[:2]>/<sha256>, so a file shared by several
# examples is downloaded once.
"""


@dataclass(frozen=True, slots=True)
class ExampleFile:
    """One file an example needs, addressed by its content hash.

    ``repo_path`` is where it lives in the HydroModPy repository, ``dest``
    where it lands under the workspace root.
    """

    repo_path: str
    dest: str
    size: int
    sha256: str


@dataclass(frozen=True, slots=True)
class ExampleEntry:
    """One catalogued example: what it is, and every file it needs."""

    id: str
    directory: str
    title: str
    summary: str
    runtime: str
    entry_config: str
    files: tuple[ExampleFile, ...]
    data: tuple[ExampleFile, ...]

    @property
    def payload(self) -> tuple[ExampleFile, ...]:
        """Every file the example needs, authored files first."""
        return self.files + self.data

    @property
    def total_size(self) -> int:
        """Total payload in bytes, whatever is already cached."""
        return sum(item.size for item in self.payload)


def catalog_path() -> Path:
    """Return the packaged ``catalog.toml`` path."""
    return Path(__file__).resolve().parent / CATALOG_FILENAME


def load_catalog(path: Path | None = None) -> tuple[ExampleEntry, ...]:
    """Read the catalog and return its entries in declaration order."""
    source = path if path is not None else catalog_path()
    if not source.is_file():
        raise FileNotFoundError(f"Example catalog not found at {source}.")
    with source.open("rb") as handle:
        document = tomllib.load(handle)

    declared = document.get("schema_version")
    if declared != SCHEMA_VERSION:
        raise FileNotFoundError(
            f"{source} declares schema_version={declared!r}, this build reads {SCHEMA_VERSION}."
        )

    return tuple(_entry_from_toml(raw) for raw in document.get("example", ()))


def find_entry(example_id: str, catalog: tuple[ExampleEntry, ...]) -> ExampleEntry:
    """Return the entry with this id, or raise naming the ids that exist."""
    for entry in catalog:
        if entry.id == example_id:
            return entry
    known = ", ".join(item.id for item in catalog) or "(none)"
    raise FileNotFoundError(f"Unknown example '{example_id}'. This build ships: {known}.")


def render_catalog(entries: tuple[ExampleEntry, ...]) -> str:
    """Serialise entries to the exact bytes ``catalog.toml`` carries.

    Hand-written rather than delegated to a TOML writer: the file is compared
    byte for byte by a test, so the emitter has to be part of the contract
    instead of following whatever a third-party writer does this release.
    """
    lines: list[str] = [_HEADER, f"schema_version = {SCHEMA_VERSION}", ""]
    for entry in entries:
        lines.append("[[example]]")
        lines.append(f"id = {_quote(entry.id)}")
        lines.append(f"directory = {_quote(entry.directory)}")
        lines.append(f"title = {_quote(entry.title)}")
        lines.append(f"summary = {_quote(entry.summary)}")
        lines.append(f"runtime = {_quote(entry.runtime)}")
        lines.append(f"entry_config = {_quote(entry.entry_config)}")
        lines.append("")
        for table, items in (("example.file", entry.files), ("example.data", entry.data)):
            for item in items:
                lines.append(f"[[{table}]]")
                lines.append(f"repo_path = {_quote(item.repo_path)}")
                lines.append(f"dest = {_quote(item.dest)}")
                lines.append(f"size = {item.size}")
                lines.append(f"sha256 = {_quote(item.sha256)}")
                lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def _entry_from_toml(raw: dict) -> ExampleEntry:
    return ExampleEntry(
        id=str(raw["id"]),
        directory=str(raw["directory"]),
        title=str(raw["title"]),
        summary=str(raw["summary"]),
        runtime=str(raw["runtime"]),
        entry_config=str(raw["entry_config"]),
        files=tuple(_file_from_toml(item) for item in raw.get("file", ())),
        data=tuple(_file_from_toml(item) for item in raw.get("data", ())),
    )


def _file_from_toml(raw: dict) -> ExampleFile:
    return ExampleFile(
        repo_path=str(raw["repo_path"]),
        dest=str(raw["dest"]),
        size=int(raw["size"]),
        sha256=str(raw["sha256"]),
    )


def _quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
