base_config = "C:/codes/HydroModPy/validation_cases/analytical/transient/linearized_unconfined_boundary_step_1d/config_modflownwt.toml"

[workspace]
project_root = "C:/codes/HydroModPy/validation_cases/analytical/transient/linearized_unconfined_boundary_step_1d"
root = "C:/codes/HydroModPy/tmp/lu_boundary_step_same_support_workspace"
output_root = "C:/codes/HydroModPy/tmp/lu_boundary_step_same_support_workspace"

[flow]
[flow.bc]
[flow.bc.dirichlet]
[flow.bc.dirichlet.west_side]
[flow.bc.dirichlet.west_side.forcing]
path_file = "C:/codes/HydroModPy/validation_cases/analytical/transient/linearized_unconfined_boundary_step_1d/west_head_step.csv"

[simulation]
run_id = "modflownwt"

[[simulation.process]]
solvers = ["modflownwt"]
