"""Outlet-to-catchment extraction.

This module converts one outlet coordinate into watershed geometries using
precomputed D8 rasters. It is the "entry point" of the V2 chain when the
catchment is defined from outlet coordinates.

Algorithm
---------
1. Write the outlet as a point shapefile.
2. Snap the outlet to the nearest valid drainage cell on accumulation raster.
3. Delineate watershed raster from D8 directions.
4. Polygonize watershed raster for downstream GIS/domain processing.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import geopandas as gpd
import pandas as pd

from hydromodpy.backends import WhiteboxBackend, get_whitebox_backend

from hydromodpy.geographic.geographic_io import ensure_crs


@dataclass(frozen=True)
class CatchmentFromPointProducts:
    """Paths to all artifacts generated by outlet-based delineation."""

    outlet_shp: str
    outlet_snap_shp: str
    watershed_tif: str
    watershed_shp: str


def extract_catchment_from_point(
    *,
    x_outlet: float,
    y_outlet: float,
    snap_dist: int,
    acc_path: str | Path,
    direc_path: str | Path,
    output_dir: str | Path,
    crs_project: str | None = None,
    outlet_name: str = "outlet.shp",
    outlet_snap_name: str = "outlet_snap.shp",
    watershed_tif_name: str = "watershed.tif",
    watershed_shp_name: str = "watershed.shp",
    backend: WhiteboxBackend | None = None,
    wbt_tool: WhiteboxBackend | None = None,
) -> CatchmentFromPointProducts:
    """Delineate a catchment polygon from one outlet point.

    Parameters
    ----------
    x_outlet, y_outlet:
        Outlet coordinates in model projected CRS.
    snap_dist:
        Max snapping distance used by Whitebox (map units, usually meters).
    acc_path, direc_path:
        D8 accumulation and direction rasters on compatible support.
    output_dir:
        Folder where output files are written.
    crs_project:
        Optional CRS enforced on generated files.
    *_name:
        Filenames used inside ``output_dir``.
    backend:
        Optional Whitebox backend for runtime/tests.
    wbt_tool:
        Legacy alias for ``backend`` kept for backward compatibility.
    """
    if backend is not None and wbt_tool is not None:
        raise ValueError("Pass either 'backend' or legacy alias 'wbt_tool', not both.")
    tool = get_whitebox_backend() if backend is None and wbt_tool is None else (backend or wbt_tool)

    # Prepare deterministic output paths used by the rest of the pipeline.
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    outlet_shp = out_dir / outlet_name
    outlet_snap_shp = out_dir / outlet_snap_name
    watershed_tif = out_dir / watershed_tif_name
    watershed_shp = out_dir / watershed_shp_name

    # Whitebox receives outlets through a point shapefile input.
    df = pd.DataFrame({"x": [float(x_outlet)], "y": [float(y_outlet)]})
    gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df["x"], df["y"]), crs=crs_project)
    gdf.to_file(str(outlet_shp))
    ensure_crs(outlet_shp, crs_project)

    # Snap stabilizes delineation when outlet is not exactly on a flow cell.
    tool.snap_pour_points(
        str(outlet_shp),
        str(acc_path),
        str(outlet_snap_shp),
        int(snap_dist),
    )
    ensure_crs(outlet_snap_shp, crs_project)

    # D8 watershed delineation from snapped outlet.
    tool.watershed(
        str(direc_path),
        str(outlet_snap_shp),
        str(watershed_tif),
        esri_pntr=False,
    )
    ensure_crs(watershed_tif, crs_project)

    # Polygon output is the canonical boundary format used downstream.
    tool.raster_to_vector_polygons(str(watershed_tif), str(watershed_shp))
    ensure_crs(watershed_shp, crs_project)

    return CatchmentFromPointProducts(
        outlet_shp=str(outlet_shp),
        outlet_snap_shp=str(outlet_snap_shp),
        watershed_tif=str(watershed_tif),
        watershed_shp=str(watershed_shp),
    )
