base_config = "project_simulation.toml"


[workflow]
mode = "simulation"

[workspace]
project_root = "outputs/vire_nwt"
root = "../../"

[simulation]
name = "vire_nwt_demo"

[simulation.time]
start_datetime = "2020-01-01 00:00:00"
end_datetime = "2020-12-31 00:00:00"
step_value = "1 month"
coverage_policy = "warn"

[geographic]
x_outlet = 400866.1983
y_outlet = 6923974.693

[[simulation.process]]
id = "flow_main"
type = "flow"
solvers = ["modflownwt"]

[modflownwt.runtime]

[modflownwt.runtime.nwt]
version = "mfnwt"
listunit = 2
verbose = false
headtol = 1e-6
fluxtol = 1e-4
maxiterout = 500
thickfact = 1e-5
linmeth = 1
iprnwt = 0
ibotav = 1
options = "SIMPLE"
continue_run = false
backflag = 0
stoptol = 1e-10

[modflownwt.runtime.dis]
itmuni = 1

[modflownwt.runtime.bas]
hnoflo = -9999.0

[modflownwt.runtime.upw]
iphdry = 1
hdry = -100.0
layvka = 1

[modflownwt.runtime.evt]
nevtop = 3
ievt = 1
ipakcb = 1

[modflownwt.runtime.oc]
compact = true

[modflownwt.runtime.wel]
ipakcb = 1

[modflownwt.runtime.lmt]
output_file_name = "mt3d_link.ftl"
extension = "lmt8"
output_format = "unformatted"
[modflownwt.sgrid.planar]
mode = "resample_to_shape"
nx = 80
ny = 80

[modflownwt.sgrid.vertical]
genmtd_lay = "decay"
nlay = 2
lay_decay = 1.2
