base_config = "project_simulation.toml"

[workspace]
project_root = "outputs/vire_mf6_regular"
root = "../../"

[simulation]
name = "vire_mf6_regular_demo"

[simulation.time]
start_datetime = "2020-01-01 00:00:00"
end_datetime = "2020-12-31 00:00:00"
step_value = "1 month"
coverage_policy = "warn"

[geographic]
x_outlet = 400866.1983
y_outlet = 6923974.693

[[simulation.process]]
id = "flow_main"
type = "flow"
solvers = ["modflow6"]

[modflow6.runtime]
mf6_ims_complexity = "COMPLEX"
mf6_outer_dvclose = 0.0001
mf6_inner_dvclose = 0.0001
mf6_outer_maximum = 1000
mf6_inner_maximum = 1000
mf6_enable_rewet = false

[modflow6.sgrid.planar]
mode = "resample_to_shape"
nx = 80
ny = 80

[modflow6.sgrid.vertical]
genmtd_lay = "decay"
nlay = 2
lay_decay = 1.2
