# HydroModPy environment file for conda users
# Usage:
#     conda env create -f environment.yml
#     conda activate hydromodpy

name: hydromodpy
channels:
    - conda-forge
    #- defaults
dependencies:
    # Obvious
    - python=3.8.10
    - ipykernel=6.2.0
    - pip=21.0.1
    - pip:
        - hydroeval
        - geopy
        - pyproj
        - contextily
        - colormap #pip install easydev may be necessary

    # Main processing libraries
    - numpy=1.21.2
    - whitebox=2.0.3
    - gdal=3.1.4
    - flopy=3.3.3
    - fastscape=0.1
    - xarray-simlab=0.5.0 # Required for FastScape, and called 'xsimlab' in the code

    # H5 files
    - pytables=3.6.1
    - deepdish=0.3.6
    - netCDF4=1.5.6

    # Data reading/writing and conversion
    - pandas=1.3.1
    - geopandas=0.9.0 # rtree failled the import of geopandas: 'conda install pygeos --channel conda-forge' and 'pip uninstall rtree'
    - imageio=2.9.0
    - rasterio=1.2.1 # 
    - pyshp=2.1.3 # corresponds to 'shapefile' library in the code
    - selenium=3.141.0
    
    # Post-processing
    - matplotlib=3.4.2
    - matplotlib-scalebar
    - vedo=2021.0.6

    # Viewing notebooks
    - jupyter=1.0.0
    - jupyterlab=3.1.0
    - spyder=5.1.5
