name: hydromodpy-01
channels:
  - conda-forge
dependencies:
  - colormap=1.0.1
  - contextily=1.6.2
  - deepdish=0.3.7
  - flopy=3.9.2
  - gdal=3.10.2
  - geopandas=1.0.1
  - imageio=2.37.0
  - ipykernel=6.29.5
  - ipython=8.35.0
  - matplotlib=3.10.1
  - matplotlib-scalebar=0.9.0
  - netcdf4=1.7.2
  - numpy=2.2.5
  - pandas=2.2.3
  - plotly=6.0.1
  - pyshp=2.3.1
  - python=3.13.2
  - rasterio=1.4.3
  - rioxarray=0.19.0
  - selenium=4.31.0
  - spyder-kernels=3.0.3
  - vedo=2025.5.3
  - whitebox=2.3.6
  - xarray=2025.3.1
