"""Launcher package for model-calibration workflows."""

from hydromodpy.analysis.calibration.engine.config import ModelCalibrationConfig
from hydromodpy.analysis.calibration.engine.launcher import ModelCalibrationLauncher
from hydromodpy.analysis.calibration.engine.objective_mapping import (
    ObjectiveMappingPoint,
    build_objective_mapping_artifacts,
    interpolate_objective_grid,
    load_objective_mapping_points,
    propose_additional_objective_mapping_params,
    resolve_objective_mapping_axes,
    run_objective_mapping,
)
from hydromodpy.analysis.calibration.engine.output_selection import (
    CanonicalOutputBundle,
    CanonicalOutputVariable,
    PreparedOutputSelector,
    canonicalize_run_outputs,
    prepare_output_selectors,
    select_candidate_outputs_from_selectors,
)
from hydromodpy.analysis.calibration.engine.property_arrays import (
    HydraulicPropertyArray,
    PropertyArraySet,
    build_property_array_set,
)
from hydromodpy.analysis.calibration.engine.reporting import (
    build_calibration_report,
    persist_calibration_report,
)
from hydromodpy.analysis.calibration.engine.session import (
    actualize_candidate,
    build_model_distribution_payload,
    CandidateRunOutcome,
    CandidateRunRequest,
    IterationRecord,
    ModelCalibrationObjectiveEvaluator,
    PreparedCalibrationSession,
    append_iteration_record,
    execute_best_candidate_rerun,
    execute_candidate_run,
    execute_model_distribution_reruns,
    evaluate_candidate_objective,
    finalize_calibration_session,
    initialize_calibration_session,
    persist_iteration_record,
    persist_model_distribution,
    prepare_calibration_session,
    serialize_calibration_result,
    select_candidate_outputs,
    select_model_distribution_samples,
    validate_objective_ready_for_calibration,
)
from hydromodpy.analysis.calibration.engine.state import ModelCalibrationState

__all__ = (
    "actualize_candidate",
    "append_iteration_record",
    "build_model_distribution_payload",
    "CandidateRunOutcome",
    "CandidateRunRequest",
    "CanonicalOutputBundle",
    "CanonicalOutputVariable",
    "PreparedOutputSelector",
    "canonicalize_run_outputs",
    "HydraulicPropertyArray",
    "execute_best_candidate_rerun",
    "execute_candidate_run",
    "execute_model_distribution_reruns",
    "evaluate_candidate_objective",
    "finalize_calibration_session",
    "initialize_calibration_session",
    "IterationRecord",
    "ModelCalibrationConfig",
    "ModelCalibrationLauncher",
    "ModelCalibrationObjectiveEvaluator",
    "ModelCalibrationState",
    "ObjectiveMappingPoint",
    "build_objective_mapping_artifacts",
    "interpolate_objective_grid",
    "load_objective_mapping_points",
    "build_calibration_report",
    "persist_iteration_record",
    "persist_calibration_report",
    "persist_model_distribution",
    "propose_additional_objective_mapping_params",
    "PropertyArraySet",
    "PreparedCalibrationSession",
    "build_property_array_set",
    "prepare_calibration_session",
    "prepare_output_selectors",
    "resolve_objective_mapping_axes",
    "run_objective_mapping",
    "serialize_calibration_result",
    "select_candidate_outputs",
    "select_candidate_outputs_from_selectors",
    "select_model_distribution_samples",
    "validate_objective_ready_for_calibration",
)
