"""Helpers to render canonical TOML templates for model-calibration."""

from __future__ import annotations

from pathlib import Path


def render_model_calibration_template() -> str:
    """Render one hand-written template for the current launcher contract."""
    lines = [
        "# Auto-generated model-calibration launcher template.",
        "# Usage:",
        "#   python -m launchers model-calibration run config_model_calibration.toml",
        "",
        "[model_calibration]",
        'simulation_config = "run_flow_reference.toml"',
        'calibration_id = "flow_case_01"',
        "disable_display = true",
        "disable_postprocess = true",
        "rerun_best_with_outputs = true",
        "persist_model_distribution = true",
        "rerun_model_distribution_with_outputs = false",
        "model_distribution_max_reruns = 10",
        'model_distribution_rerun_selection = "representative"',
        "persist_iteration_history = true",
        'persist_iteration_detail_level = "minimal"',
        "persist_calibration_report = true",
        "resume_existing_session = true",
        "reuse_persisted_iterations = true",
        "",
        "[model_calibration.objective_mapping]",
        "enabled = false",
        '# axes = ["K_global", "Sy_global"]',
        "additional_runs = 0",
        'sampling = "adaptive"',
        'interpolation = "idw"',
        "grid_size = 60",
        "candidate_pool_size = 512",
        "idw_power = 2.0",
        "random_seed = 42",
        "include_block_contributions = true",
        'output_points_csv = "objective_mapping_points.csv"',
        'output_grid_json = "objective_mapping_grid.json"',
        'output_figure = "objective_mapping.png"',
        "",
        "[calibration]",
        'objective_metric = "rmse"',
        'global_method = "cma_es"',
        "",
        "[objective]",
        'transform = "identity"',
        "",
        "[bounds]",
        "K_global = [1.0e-5, 1.0e-3]",
        "Sy_global = [0.01, 0.30]",
        "",
        "[[model_calibration.parameter]]",
        'name = "K_global"',
        'property = "K"',
        'target = "flow.param.K.field_homogeneous.value"',
        'mode = "replace"',
        'parameterization = "global_value"',
        "",
        "[[model_calibration.parameter]]",
        'name = "Sy_global"',
        'property = "Sy"',
        'target = "flow.param.Sy.field_homogeneous.value"',
        'mode = "replace"',
        'parameterization = "global_value"',
        "",
        "# Optional lithology variant:",
        '# [[model_calibration.parameter]]',
        '# name = "K_alluvium"',
        '# property = "K"',
        '# target = "flow.param.K.values_by_key.alluvium"',
        '# mode = "replace"',
        '# parameterization = "lithology_value"',
        "",
        "[[model_calibration.output]]",
        'name = "pz_01"',
        'variable = "watertable_elevation"',
        'source = "runtime"',
        'support = "point"',
        "x = 845123.0",
        "y = 6543210.0",
        'time = "all"',
        'reducer = "weighted_interpolation"',
        "# observed_values = [123.4, 123.1, 122.9]",
        "",
        "[[model_calibration.output]]",
        'name = "q_outlet_lowflow_mean"',
        'variable = "outlet_discharge"',
        'source = "runtime"',
        'support = "boundary"',
        'boundary_id = "east_side"',
        'time_window = ["2020-08-01", "2020-09-30"]',
        'time_reducer = "mean"',
        'reducer = "sum"',
        "# observed_values = [0.052]",
        "",
        "[[model_calibration.objective_block]]",
        'name = "heads"',
        'metric = "rmse"',
        "weight = 1.0",
        'uses_outputs = ["pz_01"]',
        "normalize_cost = true",
        "",
        "[[model_calibration.objective_block]]",
        'name = "flux"',
        'metric = "rmse"',
        "weight = 1.0",
        'uses_outputs = ["q_outlet_lowflow_mean"]',
        "normalize_cost = true",
        "",
        "[calibration_method.cma_es]",
        "sigma0 = 0.20",
        "popsize = 12",
        "max_evaluations = 120",
        "seed = 42",
        "normalize = true",
    ]
    return "\n".join(lines) + "\n"


def write_model_calibration_template(output_path: str | Path) -> None:
    """Render and write one model-calibration template to disk."""
    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(render_model_calibration_template(), encoding="utf-8")


__all__ = (
    "render_model_calibration_template",
    "write_model_calibration_template",
)
