# HydroModPy environment file for conda users
# Usage:
#     conda env create -f environment.yml
#     conda activate hydromodpy

name: hydromodpy
channels:
    - conda-forge
    - defaults
dependencies:
    # Obvious
    - python

    # Main processing libraries
    - numpy
    - whitebox
    - gdal
    - flopy

    #H5 files
    - pytables
    - deepdish	

    # Data reading/writing and conversion
    - pandas
    - geopandas #rtree failled the import of geopandas: 'conda install pygeos --channel conda-forge' and 'pip uninstall rtree'
    - imageio
    - rasterio
    - pyshp # corresponds to 'shapefile' library in the code

    # Post-processing
    - matplotlib

    # Viewing notebooks
    - jupyter
