"""The time unit a run declares must be the one it was built in.

A launcher run is built in SI seconds. If the MODFLOW declaration, the value
the extractors read back, or the tracking clock disagrees with that by one
step, every flux or travel time it touches is off by a factor 86400 and
nothing raises. These tests pin the three places that could drift.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import zarr

from hydromodpy.core.time import SIMULATION_TIME_UNIT
from hydromodpy.core.units import to_modflow_itmuni
from hydromodpy.solver.modflow_common.time_units import (
    TRACKING_TIME_UNIT,
    factor_to_tracking_unit,
    read_itmuni_from_dis,
    read_time_units_from_tdis,
    resolve_solver_time_unit,
    seconds_per_solver_time_unit,
)
from hydromodpy.solver.modflow_grid.discretization_temporal import (
    build_temporal_discretization_from_time_grid,
)
from hydromodpy.solver.modflow_nwt.extractors.modpath import ModpathOutputAdapter


class _ZarrHandle:
    def __init__(self, path: Path):
        self.root = zarr.open_group(str(path), mode="a")

    def close(self) -> None:
        pass


class _Store:
    def __init__(self, root: Path):
        self.root = root

    def open_zarr(self, sim_id: str) -> _ZarrHandle:
        return _ZarrHandle(self.root / f"{sim_id}.zarr")


class _TimeGrid:
    period_lengths_seconds = (86400.0, 86400.0)
    nstp_per_period = 1
    window = None


def _write_tdis(directory: Path, token: str) -> None:
    (directory / "case.tdis").write_text(
        f"BEGIN options\n  TIME_UNITS  {token}\nEND options\n", encoding="utf-8"
    )


def _write_dis(directory: Path, model_name: str, itmuni: int) -> None:
    """Write the header FloPy emits: a comment, NLAY NROW NCOL NPER ITMUNI LENUNI, LAYCBD."""
    (directory / f"{model_name}.dis").write_text(
        f"# DIS package for MODFLOW-2005 generated by Flopy\n"
        f"         1         2         2         1         {itmuni}         2\n"
        f"  0\n",
        encoding="utf-8",
    )


def test_temporal_result_states_one_unit_in_both_forms() -> None:
    result = build_temporal_discretization_from_time_grid(
        time_grid=_TimeGrid(), flow_regime="transient"
    )

    assert result.time_units == SIMULATION_TIME_UNIT
    assert result.itmuni == to_modflow_itmuni(result.time_units)


def test_undeclared_unit_resolves_to_the_launcher_unit(tmp_path: Path) -> None:
    # No TDIS, no DIS: the caller must not silently get days.
    assert resolve_solver_time_unit(tmp_path, "case") == SIMULATION_TIME_UNIT
    assert seconds_per_solver_time_unit(tmp_path, "case") == 1.0


def test_unknown_tdis_token_resolves_to_the_launcher_unit(tmp_path: Path) -> None:
    _write_tdis(tmp_path, "UNKNOWN")

    assert resolve_solver_time_unit(tmp_path, "case") == SIMULATION_TIME_UNIT


@pytest.mark.parametrize(("token", "expected"), [("SECONDS", 1.0), ("DAYS", 86400.0)])
def test_tdis_declaration_wins(tmp_path: Path, token: str, expected: float) -> None:
    _write_tdis(tmp_path, token)

    assert read_time_units_from_tdis(tmp_path / "case.tdis") == token
    assert seconds_per_solver_time_unit(tmp_path, "case") == expected


def test_nwt_falls_back_to_the_dis_itmuni(tmp_path: Path) -> None:
    _write_dis(tmp_path, "flow", itmuni=4)

    assert read_itmuni_from_dis(tmp_path / "flow.dis") == 4
    assert resolve_solver_time_unit(tmp_path, "flow") == "days"


def test_modpath_stores_the_tracking_unit_it_declares(tmp_path: Path, monkeypatch) -> None:
    output_dir = tmp_path / "solver"
    output_dir.mkdir()
    _write_dis(output_dir, "flow", itmuni=to_modflow_itmuni(SIMULATION_TIME_UNIT))
    (output_dir / "flow.mppth").write_text("", encoding="utf-8")

    particle = np.zeros(2, dtype=[("x", "f8"), ("y", "f8"), ("z", "f8"), ("time", "f8")])
    particle["time"] = [0.0, 172800.0]

    class _FakePathlineFile:
        def __init__(self, path: str) -> None:
            del path

        def get_alldata(self):
            return [particle]

    monkeypatch.setattr("flopy.utils.PathlineFile", _FakePathlineFile)
    store = _Store(tmp_path / "catalog")

    ModpathOutputAdapter().extract("sim_mp", output_dir, store, model_name="flow")

    handle = store.open_zarr("sim_mp")
    try:
        time = np.asarray(handle.root["particles/time"])
        attrs = dict(handle.root["particles"].attrs)
    finally:
        handle.close()

    # A MODFLOW-NWT run built in seconds: 172800 s is 2 days, not 172800 days.
    assert attrs["time_units"] == TRACKING_TIME_UNIT
    assert np.allclose(time[0], [0.0, 2.0])


def test_tracking_factor_is_the_inverse_of_a_day() -> None:
    assert factor_to_tracking_unit(SIMULATION_TIME_UNIT) == pytest.approx(1.0 / 86400.0)
    assert factor_to_tracking_unit(TRACKING_TIME_UNIT) == 1.0
