"""``hmp data get`` - fetch an upstream variable into the workspace cache."""

from __future__ import annotations

import argparse
import sys
from datetime import UTC, datetime

from hydromodpy.cli.helpers import EXIT_CONFIG, resolve_workspace

NAME: str = "get"
HELP: str = "Fetch an upstream variable and write a JSON sidecar next to the file"


def _parse_bbox(value: str) -> tuple[float, float, float, float]:
    parts = value.split(",")
    if len(parts) != 4:
        raise argparse.ArgumentTypeError(
            "bbox must be 'minx,miny,maxx,maxy' (four comma-separated floats); "
            "use '--bbox=-1.17,48.4,-1.0,48.5' when minx is negative"
        )
    try:
        floats = tuple(float(p) for p in parts)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"bbox values must be floats ({exc})") from exc
    return (floats[0], floats[1], floats[2], floats[3])


def register(subparsers) -> argparse.ArgumentParser:
    parser = subparsers.add_parser(NAME, help=HELP)
    parser.add_argument("variable", help="Variable name (e.g. dem, piezometry, hydrometry)")
    parser.add_argument(
        "--bbox",
        default=None,
        type=_parse_bbox,
        metavar="MINX,MINY,MAXX,MAXY",
        help=(
            "Bounding box minx,miny,maxx,maxy in the workspace CRS. "
            "When minx is negative, use '--bbox=-1.17,48.4,-1.0,48.5' (= sign)."
        ),
    )
    parser.add_argument("--workspace", default=None)
    parser.add_argument(
        "--source",
        default="upstream",
        help="Free-form label recorded in the sidecar (default: upstream)",
    )
    parser.set_defaults(_handler=run)
    return parser


def run(args: argparse.Namespace) -> None:
    from hydromodpy.data.scaffold import VARIABLES
    from hydromodpy.data.sidecars import (
        Sidecar,
        compute_sha256,
        resolve_fetched_at,
        write_sidecar,
    )

    workspace = resolve_workspace(args.workspace)
    spec = next((s for s in VARIABLES if s.name == args.variable), None)
    if spec is None:
        names = ", ".join(s.name for s in VARIABLES)
        print(f"Unknown variable {args.variable!r}. Available: {names}", file=sys.stderr)
        sys.exit(EXIT_CONFIG)

    bbox: tuple[float, float, float, float] | None = args.bbox
    raw_dir = workspace / "data" / spec.name / "raw"
    raw_dir.mkdir(parents=True, exist_ok=True)

    suffix = {
        "raster": ".tif",
        "vector": ".gpkg",
        "timeseries": ".parquet",
    }.get(spec.kind, ".bin")
    stamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    target = raw_dir / f"{spec.name}_{stamp}{suffix}"

    payload = (
        f"placeholder fetch for variable={spec.name} bbox={bbox} "
        f"at {datetime.now(UTC).isoformat()}\n"
    )
    target.write_bytes(payload.encode("utf-8"))

    sidecar = Sidecar(
        source=args.source,
        fetched_at=resolve_fetched_at(args.source),
        sha256=compute_sha256(target),
        license=None,
        crs=None,
        bbox=bbox,
        notes=f"auto-generated by 'hmp data get {spec.name}'",
    )
    sidecar_path = write_sidecar(target, sidecar)

    print(f"  Fetched {spec.name} -> {target}")
    print(f"  Sidecar  -> {sidecar_path}")
