base_config = "project.toml"

workflow = "simulation"

[simulation]
name = "Example 12 launcher fast"

[simulation.time]
start_datetime = "2003-01-01 00:00:00"
end_datetime = "2003-03-31 00:00:00"
step_value = "30 day"
coverage_policy = "warn"

[flow.sinks_sources.wells.W1.forcing]
path_file = "../../../examples/data/wells/normal_wells_2003.csv"

[flow.sinks_sources.wells.W2]
x_rel = 0.33
y_rel = 0.33

[flow.sinks_sources.wells.W2.forcing]
path_file = "../../../examples/data/wells/normal_wells_2003.csv"

[data]
types = ["recharge"]

[[data.recharge.sources]]
source = "synthetic"
values = [2.0, 2.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0]
freq = "MS"
runoff_ratio = 0.1

[display]
show = false
