# Dockerfile for image to run LoopAggregation example
FROM ubuntu:20.04

# System packages
RUN apt-get update && \
DEBIAN_FRONTEND=noninteractive \
TZ=Europe \
apt-get install libgfortran5 python3 python3-pip libgdal-dev python3-gdal libgl1-mesa-glx libxt6 bsdmainutils spyder -y

RUN pip3 -q install pip --upgrade

# Python packages
RUN pip3 install --ignore-installed pyzmq

RUN pip3 install pandas flopy matplotlib scipy vtk jupyterlab jupyter notebook


# Add modflow project in the docker
COPY . ~/LoopAggregation/

# Default folder
WORKDIR ~/LoopAggregation


# Add Tini. Tini operates as a process subreaper for jupyter. This prevents kernel crashes.
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT ["/usr/bin/tini", "--"]

CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]


# Add modflow project in the docker
#COPY . /LoopAggregation/

# Default folder
#WORKDIR /modflow
