# Usage:
#     conda env create -f environment.yml
#     conda activate loopagg


name: loopagg

channels:
    - conda-forge

dependencies:
    - python=3.10.2
    - pip=21.0

    - pandas
    - flopy=3.3.3
    - matplotlib
    - numpy
    - scipy=1.8.0
    - gdal

