# Usage:
#     conda env create -f environment.yml
#     conda activate loopagg


name: loopagg

dependencies:
    - python=3.10
    - pip

    - pandas
    - flopy
    - matplotlib
    - numpy
    - scipy
    - GDAL
    - spyder

