# Usage:
#     conda env create -f environment.yml
#     conda activate loopagg


name: loopagg

channels:
    - conda-forge

dependencies:
    - python
    - pip

    - pandas
    - flopy
    - matplotlib
    - numpy
    - scipy
    - gdal
    - spyder

