"""Generate the documentation tables that a declared contract already owns.

Companion to ``tools/doc_config``, which does the same job for the Pydantic
configuration tree. Everything here follows the same three rules:

1. read a contract that already exists and is already enforced by a test;
2. assert the contract before rendering it, because a generator republishes
   whatever it is given and a faithful copy of a wrong fact is still wrong;
3. carry a regenerate-and-compare gate, because a generator without a gate is
   one more thing to maintain rather than one less.

Run by hand with ``python -m tools.doc_contracts``. Called from the
``builder-inited`` hook in ``docs/source/conf.py`` so every build refreshes it.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
LAYER_MATRIX_YAML = Path("tests/unit/architecture/layer_matrix.yaml")
LAYER_MATRIX_PAGE = Path("docs/source/architecture/layer-matrix.partial.rst")

GENERATED_HEADER = (
    ".. AUTO-GENERATED by tools/doc_contracts. Do not edit by hand.\n"
    ".. Source of truth: tests/unit/architecture/layer_matrix.yaml\n"
    ".. Run ``python -m tools.doc_contracts`` to refresh.\n\n"
)

# The one key in ``allowed`` that is not a package: the top-level
# ``hydromodpy/`` namespace itself.
ROOT_KEY = "<root>"

# Width at which a row's target list wraps. The repository caps RST lines at
# 130; this keeps the generated table comfortably inside a diff.
_WRAP = 66


def _write_if_changed(path: Path, content: str) -> bool:
    """Write only on a real change, so sphinx-autobuild does not loop."""
    try:
        if path.read_text(encoding="utf-8") == content:
            return False
    except FileNotFoundError:
        pass
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def load_layer_matrix(path: Path | None = None) -> dict[str, Any]:
    target = (path or REPO_ROOT / LAYER_MATRIX_YAML).resolve()
    return yaml.safe_load(target.read_text(encoding="utf-8"))


def assert_layer_matrix_inputs(matrix: dict[str, Any]) -> list[str]:
    """Check the contract before rendering it. Returns the problems found.

    Without this the generator would happily publish a layer that does not
    exist. The page it replaces carried exactly that: a ``validity_frame`` row
    that is not a key of ``allowed`` and not a package on disk, alongside a
    missing ``discretization`` row that is both.
    """
    problems: list[str] = []
    allowed = matrix.get("allowed") or {}

    for layer in allowed:
        if layer == ROOT_KEY:
            continue
        if importlib.util.find_spec(f"hydromodpy.{layer}") is None:
            problems.append(f"allowed declares {layer!r}, which is not an importable package")

    known = set(allowed)
    for layer, targets in allowed.items():
        for target in targets or []:
            if target not in known:
                problems.append(
                    f"{layer!r} is granted an edge to {target!r}, which is not a declared layer"
                )

    for entry in matrix.get("tolerances") or []:
        for side in ("src", "tgt"):
            if entry.get(side) not in known:
                problems.append(
                    f"tolerance {entry} names {side}={entry.get(side)!r}, which is not a declared layer"
                )
        if not (entry.get("reason") or "").strip():
            problems.append(f"tolerance {entry.get('src')} -> {entry.get('tgt')} carries no reason")

    for rel in matrix.get("exempt_files") or []:
        if not (REPO_ROOT / rel).exists():
            problems.append(f"exempt_files lists {rel}, which does not exist")

    return problems


def _wrap_targets(targets: list[str], indent: str) -> list[str]:
    cells = [f"``{t}``" for t in targets]
    lines: list[str] = []
    current = ""
    for cell in cells:
        candidate = f"{current}, {cell}" if current else cell
        if len(candidate) > _WRAP and current:
            lines.append(current + ",")
            current = cell
        else:
            current = candidate
    if current:
        lines.append(current)
    return [f"{indent}{line}" for line in lines]


def render_layer_matrix(matrix: dict[str, Any]) -> str:
    allowed = matrix["allowed"]
    tolerances = matrix.get("tolerances") or []
    exempt = matrix.get("exempt_files") or []

    lines: list[str] = [
        GENERATED_HEADER.rstrip("\n"),
        "",
        "Layer matrix",
        "------------",
        "",
        f"{len(allowed)} layers, {sum(len(v or []) for v in allowed.values())} granted edges. "
        "A layer always implicitly allows imports targeting itself; anything absent from a row",
        "is forbidden and fails CI.",
        "",
        ".. list-table::",
        "   :header-rows: 1",
        "   :widths: 16 84",
        "",
        "   * - Source layer",
        "     - Allowed import targets",
    ]
    for layer, targets in allowed.items():
        lines.append(f"   * - ``{layer}``")
        wrapped = _wrap_targets(list(targets or []), "       ")
        lines.append("     - " + wrapped[0].strip())
        lines.extend(wrapped[1:])

    lines += [
        "",
        "Documented tolerances",
        "---------------------",
        "",
        f"{len(tolerances)} edges are tolerated rather than granted. Each one carries its reason in the",
        "contract. They are temporary or deliberately narrow; tighten one when the edge disappears.",
        "",
        ".. list-table::",
        "   :header-rows: 1",
        "   :widths: 14 14 72",
        "",
        "   * - From",
        "     - To",
        "     - Why",
    ]
    for entry in tolerances:
        lines.append(f"   * - ``{entry['src']}``")
        lines.append(f"     - ``{entry['tgt']}``")
        lines.append(f"     - {entry['reason']}")

    lines += [
        "",
        "Files exempt from the layer rule",
        "--------------------------------",
        "",
        f"{len(exempt)} files are exempt: bootstrap shims that wire forward references, and the case",
        "runners that load a user TOML and belong semantically to ``examples/``.",
        "",
    ]
    lines.extend(f"- ``{rel}``" for rel in exempt)
    lines.append("")
    return "\n".join(lines) + "\n"


def generate_layer_matrix(output_path: Path | None = None) -> Path:
    """Render the layer-matrix page fragment. Raises if the contract is unsound."""
    matrix = load_layer_matrix()
    problems = assert_layer_matrix_inputs(matrix)
    if problems:
        joined = "\n  - ".join(problems)
        raise ValueError(f"layer_matrix.yaml is not a sound contract:\n  - {joined}")
    target = (output_path or REPO_ROOT / LAYER_MATRIX_PAGE).resolve()
    _write_if_changed(target, render_layer_matrix(matrix))
    return target


def generate_all() -> list[Path]:
    return [generate_layer_matrix()]


if __name__ == "__main__":
    for written in generate_all():
        print(f"wrote {written}")
