"""The committed process descriptions, and the drift that must never happen.

A generated artefact without a gate drifts: the OpenAPI wrapper next door is
generated by ``tools/doc_config`` and compared by nothing, and it has. So the
first assertion here is the byte comparison, and everything after it is about
what the document may not claim.
"""

from __future__ import annotations

from typing import Any, get_args

import pytest
from jsonschema import Draft202012Validator

from hydromodpy.cli._workers.process import capability_decls, capability_ids, describe_capability
from hydromodpy.cli.helpers import exit_code_for
from hydromodpy.core.exceptions import JobUsageError
from hydromodpy.schema.capability import NAMES_THE_JOB_DOES_NOT_PRODUCE
from hydromodpy.schema.job.outcome import (
    DISMISSED_STATUS,
    UNIDENTIFIED_JOB,
    JobStatus,
    dismissed,
    now,
)
from hydromodpy.schema.processes import (
    INDEX_FILENAME,
    described_ids,
    description_filename,
    read_description,
    read_index,
)
from tools.processes.generate import DESCRIPTIONS_DIR, render_all

REFRESH = "python -m tools.processes"


def _committed(name: str) -> str:
    return (DESCRIPTIONS_DIR / name).read_text(encoding="utf-8")


def _nodes_with_examples(node: Any) -> list[dict[str, Any]]:
    """Return every sub-schema that publishes examples of itself."""
    found: list[dict[str, Any]] = []
    if isinstance(node, dict):
        if "examples" in node:
            found.append(node)
        for value in node.values():
            found.extend(_nodes_with_examples(value))
    elif isinstance(node, list):
        for item in node:
            found.extend(_nodes_with_examples(item))
    return found


@pytest.mark.parametrize("name", sorted(render_all()))
def test_the_committed_file_is_what_the_generator_writes(name: str) -> None:
    assert _committed(name) == render_all()[name], (
        f"hydromodpy/schema/processes/{name} is stale. Run `{REFRESH}` to refresh."
    )


def test_the_generator_owns_every_json_file_that_is_committed() -> None:
    on_disk = {path.name for path in DESCRIPTIONS_DIR.glob("*.json")}
    assert on_disk == set(render_all()), (
        f"a JSON file under hydromodpy/schema/processes/ has no generator. Run `{REFRESH}`."
    )


def test_the_index_names_every_capability_this_build_declares() -> None:
    assert described_ids() == capability_ids()


def test_every_index_entry_points_at_a_file_that_reads() -> None:
    for entry in read_index()["processes"]:
        assert entry["file"] == description_filename(entry["id"], entry["major"])
        assert read_description(entry["id"], entry["major"])["id"] == entry["id"]


def test_the_index_is_not_described_as_a_process() -> None:
    assert INDEX_FILENAME not in {entry["file"] for entry in read_index()["processes"]}


@pytest.mark.parametrize("decl", capability_decls(), ids=lambda decl: decl.id)
def test_the_description_declares_the_inputs_the_model_accepts(decl) -> None:
    document = read_description(decl.id)
    assert set(document["inputs"]) == set(decl.request_model.model_fields)


@pytest.mark.parametrize("decl", capability_decls(), ids=lambda decl: decl.id)
def test_every_embedded_input_schema_is_a_valid_2020_12_document(decl) -> None:
    for name, entry in read_description(decl.id)["inputs"].items():
        assert entry["schema"]["$schema"] == "https://json-schema.org/draft/2020-12/schema", name
        Draft202012Validator.check_schema(entry["schema"])


@pytest.mark.parametrize("decl", capability_decls(), ids=lambda decl: decl.id)
def test_no_published_example_is_refused_by_the_schema_that_publishes_it(decl) -> None:
    """An example its own schema rejects is a lie a shim would paste into a request."""
    checked = 0
    for name, entry in read_description(decl.id)["inputs"].items():
        for node in _nodes_with_examples(entry["schema"]):
            assert "$ref" not in node, f"{name}: an example sits next to a $ref, unresolvable here"
            validator = Draft202012Validator(node)
            for example in node["examples"]:
                validator.validate(example)
                checked += 1
    assert checked, f"{decl.id} publishes no example at all"


@pytest.mark.parametrize("decl", capability_decls(), ids=lambda decl: decl.id)
def test_the_description_cannot_claim_an_exit_code_the_mapper_does_not_produce(decl) -> None:
    declared = {
        entry["code"]: entry["exit_code"] for entry in read_description(decl.id)["hmp:exceptions"]
    }
    for exc_cls in decl.exceptions:
        code = getattr(exc_cls, "code", None)
        code = code if isinstance(code, str) else exc_cls.__name__
        assert declared[code] == exit_code_for(exc_cls.__new__(exc_cls))
    assert len(declared) == len(decl.exceptions)


@pytest.mark.parametrize("decl", capability_decls(), ids=lambda decl: decl.id)
def test_the_description_declares_the_paths_the_capability_declares(decl) -> None:
    outputs = read_description(decl.id)["outputs"]
    assert set(outputs) == set(decl.output_ids)
    for output in decl.outputs:
        entry = outputs[output.id]
        assert entry["hmp:path"] == output.path
        assert entry["hmp:role"] == list(output.roles)
        assert entry["schema"]["contentMediaType"] == output.media_type
        assert entry["hmp:path"] not in NAMES_THE_JOB_DOES_NOT_PRODUCE


@pytest.mark.parametrize("decl", capability_decls(), ids=lambda decl: decl.id)
def test_the_invocation_block_names_the_verb_that_runs_it(decl) -> None:
    invocation = read_description(decl.id)["hmp:invocation"]
    assert invocation["argv"][:4] == ["hmp", "process", "run", decl.id]
    assert invocation["env"] == list(decl.env)
    assert invocation["cancellation"]["status"] in get_args(JobStatus)


@pytest.mark.parametrize("decl", capability_decls(), ids=lambda decl: decl.id)
def test_the_writable_locations_are_a_list_and_not_a_boolean(decl) -> None:
    """``false`` was published once, and it was false.

    A boolean answers "does it write elsewhere"; what an orchestrator mounting
    everything but the job directory read-only needs is "*where*". An empty list
    is the honest spelling of "nowhere", and it stays falsy for a caller who only
    asked the first question.
    """
    declared = read_description(decl.id)["hmp:invocation"]["writes_outside_jobdir"]
    assert declared == list(decl.writes_outside_jobdir)
    assert isinstance(declared, list)


def test_the_cancelled_status_the_generator_writes_is_the_one_a_job_really_writes() -> None:
    """Against the writer, not against the type.

    The constant now lives in ``schema/job/outcome.py`` and is annotated
    ``JobStatus``, so checking it against the type is a tautology a type checker
    already refuses to let fail. What can still drift is the document: this
    builds a cancelled outcome and reads the status off it.
    """
    assert DISMISSED_STATUS in get_args(JobStatus)
    cancelled = dismissed(
        job_id=UNIDENTIFIED_JOB,
        process_id="demo-delineate",
        process_version="1.2.3",
        started_at=now(),
        exc=KeyboardInterrupt(),
    )

    assert cancelled.to_document()["status"] == DISMISSED_STATUS


@pytest.mark.parametrize("decl", capability_decls(), ids=lambda decl: decl.id)
def test_the_invocation_block_promises_nothing_this_tree_does_not_do(decl) -> None:
    """Three members of the specification stay out until something makes them true.

    ``progress_file`` names ``progress.ndjson``, which no code path writes yet;
    ``network`` and ``concurrency`` are enforced by nothing. A description is
    read by a caller who cannot check it, so an unbacked claim there is worse
    than a missing member.
    """
    invocation = read_description(decl.id)["hmp:invocation"]
    assert not {"progress_file", "network", "concurrency"} & set(invocation)


def test_describing_an_unknown_capability_is_an_invocation_error() -> None:
    with pytest.raises(JobUsageError, match="no process description for 'nope'"):
        describe_capability("nope")


def test_describing_a_major_this_build_does_not_serve_is_an_invocation_error() -> None:
    with pytest.raises(JobUsageError, match="at major 99"):
        describe_capability(capability_ids()[0], 99)


def test_the_worker_reads_the_committed_bytes_and_does_not_re_render_them() -> None:
    capability_id = capability_ids()[0]
    entry = next(e for e in read_index()["processes"] if e["id"] == capability_id)
    assert describe_capability(capability_id) == _committed(entry["file"])
