"""Generate the static illustrated capability gallery used by the docs."""

from __future__ import annotations

import argparse
import hashlib
import importlib
import json
from dataclasses import replace
from pathlib import Path
import shutil
import tempfile
from typing import Any

import numpy as np

from tools.mesh_bundle_viewer.runner.visualization_runner import (
    load_toml_config,
    run_visualization,
)

from .gallery_manifest import (
    CATEGORY_SPECS,
    GalleryCaseSpec,
    build_gallery_specs,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_SOURCE_DIR = REPO_ROOT / "docs" / "readthedocs" / "source"
TEXTUAL_SUFFIXES = {".json", ".rst"}
AUTO_GENERATED_COMMENT = ".. This file is auto-generated by ``python -m tools.doc_gallery``."
AUTO_GENERATED_NOTE = (
    "This page and its static assets are auto-generated by ``python -m tools.doc_gallery``. "
    "The Sphinx build only reads committed PNG and JSON artifacts."
)


def build_parser() -> argparse.ArgumentParser:
    """Build the public command-line parser."""

    parser = argparse.ArgumentParser(
        description=(
            "Generate or verify the static illustrated capability gallery used in the docs."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Regenerate the gallery in a temporary directory and verify that the committed "
            "text artifacts are in sync. PNG presence is checked, while staleness is tracked "
            "through source hashes stored in the generated JSON summaries."
        ),
    )
    return parser


def _repo_path(relative_path: str) -> Path:
    return (REPO_ROOT / Path(relative_path)).resolve()


def _repo_relative(path: str | Path) -> str:
    path_obj = Path(path).resolve() if not isinstance(path, Path) else path.resolve()
    try:
        return path_obj.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path_obj.as_posix()


def _docs_relative_static_path(*parts: str) -> str:
    return (Path("_static") / "capability_gallery" / Path(*parts)).as_posix()


def _repo_docs_artifact_path(*parts: str) -> str:
    return (Path("docs") / "readthedocs" / "source" / "_static" / "capability_gallery" / Path(*parts)).as_posix()


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _json_ready(value: Any) -> Any:
    if isinstance(value, Path):
        return _repo_relative(value)
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, dict):
        return {str(key): _json_ready(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_json_ready(item) for item in value]
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return str(value)


def _build_source_hashes(source_paths: tuple[str, ...]) -> dict[str, str]:
    hashes: dict[str, str] = {}
    for relative_path in source_paths:
        hashes[relative_path] = _sha256(_repo_path(relative_path))
    return hashes


def _import_symbol(import_path: str):
    module_name, symbol_name = import_path.split(":", 1)
    module = importlib.import_module(module_name)
    return getattr(module, symbol_name)


def _reset_generated_dirs(source_root: Path) -> None:
    for relative_path in (
        Path("capability_gallery"),
        Path("_static") / "capability_gallery",
    ):
        target = source_root / relative_path
        if target.exists():
            shutil.rmtree(target)
        target.mkdir(parents=True, exist_ok=True)


def _build_case_summary(
    spec: GalleryCaseSpec,
    *,
    metrics_source: dict[str, Any],
    metadata: dict[str, Any],
) -> dict[str, Any]:
    images = []
    for asset in spec.image_assets:
        static_doc_path = "/" + _docs_relative_static_path(spec.category, asset.filename)
        images.append(
            {
                "filename": asset.filename,
                "caption": asset.caption,
                "alt_text": asset.alt_text,
                "doc_path": static_doc_path,
                "repo_path": _repo_docs_artifact_path(spec.category, asset.filename),
            }
        )

    summary_json_doc_path = "/" + _docs_relative_static_path(spec.category, f"{spec.slug}_summary.json")
    summary_json_repo_path = _repo_docs_artifact_path(spec.category, f"{spec.slug}_summary.json")

    metrics = []
    for metric_spec in spec.metric_specs:
        raw_value = metrics_source[metric_spec.key]
        metrics.append(
            {
                "label": metric_spec.label,
                "key": metric_spec.key,
                "value": _json_ready(raw_value),
                "display": metric_spec.formatter(raw_value),
            }
        )

    return {
        "summary_schema_version": "capability_gallery_case_v1",
        "slug": spec.slug,
        "title": spec.title,
        "category": spec.category,
        "deck": spec.deck,
        "summary": spec.summary,
        "what_it_shows": list(spec.what_it_shows),
        "reproduction_command": spec.reproduction_command,
        "gallery_update_command": "python -m tools.doc_gallery",
        "source_paths": list(spec.source_paths),
        "source_hashes": _build_source_hashes(spec.source_paths),
        "docname": f"cases/{spec.slug}",
        "images": images,
        "metrics": metrics,
        "metadata": _json_ready(metadata),
        "artifacts": {
            "summary_json_doc_path": summary_json_doc_path,
            "summary_json_repo_path": summary_json_repo_path,
            "image_repo_paths": [image["repo_path"] for image in images],
        },
    }


def _generate_mesh_viewer_case(spec: GalleryCaseSpec, source_root: Path) -> dict[str, Any]:
    figure_path = source_root / _docs_relative_static_path(spec.category, spec.image_assets[0].filename)
    config = load_toml_config(_repo_path(str(spec.metadata["config_path"])))
    config = replace(
        config,
        figure_output_path=figure_path.resolve(),
        summary_output_path=None,
        show_window=False,
    )
    raw_summary = run_visualization(config)
    sanitized_viewer_summary = {
        key: _json_ready(value)
        for key, value in raw_summary.items()
        if key not in {"figure_output_path", "summary_output_path"}
    }
    if "bundle_dir" in raw_summary:
        sanitized_viewer_summary["bundle_dir"] = _repo_relative(str(raw_summary["bundle_dir"]))
    if "mesh_file" in raw_summary:
        sanitized_viewer_summary["mesh_file"] = _repo_relative(str(raw_summary["mesh_file"]))

    return _build_case_summary(
        spec,
        metrics_source={metric.key: raw_summary[metric.key] for metric in spec.metric_specs},
        metadata={
            "config_path": str(spec.metadata["config_path"]),
            "viewer_summary": sanitized_viewer_summary,
        },
    )


def _generate_copy_assets_case(spec: GalleryCaseSpec, source_root: Path) -> dict[str, Any]:
    copied_assets = []
    for asset in spec.image_assets:
        if asset.source_path is None:
            raise ValueError(f"Gallery asset {asset.filename} is missing source_path.")
        destination = source_root / _docs_relative_static_path(spec.category, asset.filename)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(_repo_path(asset.source_path), destination)
        copied_assets.append(
            {
                "source_path": asset.source_path,
                "copied_to": _repo_docs_artifact_path(spec.category, asset.filename),
            }
        )

    return _build_case_summary(
        spec,
        metrics_source={},
        metadata={
            "copied_assets": copied_assets,
        },
    )


def _generate_validation_case(spec: GalleryCaseSpec, source_root: Path) -> dict[str, Any]:
    comparison_runner = _import_symbol(str(spec.metadata["comparison_import"]))
    plotting_function = _import_symbol(str(spec.metadata["plotting_import"]))
    figure_path = source_root / _docs_relative_static_path(spec.category, spec.image_assets[0].filename)
    comparison = comparison_runner(
        caller_file=_repo_path(str(spec.metadata["caller_file"])),
        timeout=int(spec.metadata.get("timeout", 1800)),
        solver=str(spec.metadata.get("solver", "modflownwt")),
    )
    plotting_function(comparison, output_png=figure_path, show_plot=False)

    metadata = {
        "case_dir": _repo_relative(_repo_path(str(spec.metadata["caller_file"])).parent),
        "solver": str(spec.metadata.get("solver", "modflownwt")),
        "observable_name": getattr(comparison, "observable_name", None),
        "case_metadata": getattr(comparison, "metadata", {}),
        "tolerances": getattr(comparison, "tolerances", {}),
    }
    if hasattr(comparison, "solver"):
        metadata["comparison_solver"] = getattr(comparison, "solver")
    if hasattr(comparison, "timestep"):
        metadata["timestep"] = getattr(comparison, "timestep")
    if hasattr(comparison, "final_elapsed_days"):
        metadata["final_elapsed_days"] = getattr(comparison, "final_elapsed_days")

    return _build_case_summary(
        spec,
        metrics_source={metric.key: getattr(comparison, metric.key) for metric in spec.metric_specs},
        metadata=metadata,
    )


def _generate_case(spec: GalleryCaseSpec, source_root: Path) -> dict[str, Any]:
    if spec.generator == "mesh_viewer":
        return _generate_mesh_viewer_case(spec, source_root)
    if spec.generator == "copy_assets":
        return _generate_copy_assets_case(spec, source_root)
    if spec.generator == "validation_case":
        return _generate_validation_case(spec, source_root)
    raise ValueError(f"Unsupported gallery generator kind: {spec.generator}")


def _render_note_block() -> list[str]:
    return [
        ".. note::",
        f"   {AUTO_GENERATED_NOTE}",
        "",
    ]


def _render_grid_card(*, link: str, title: str, deck: str) -> list[str]:
    return [
        "   .. grid-item-card::",
        "      :class-card: sd-shadow-sm sd-rounded-3 sd-p-4",
        f"      :link: {link}",
        "      :link-type: doc",
        "",
        f"      **{title}**",
        "      ^^^",
        f"      {deck}",
        "",
    ]


def _build_index_page(cases_by_category: dict[str, list[dict[str, Any]]]) -> str:
    lines = [
        AUTO_GENERATED_COMMENT,
        "",
        "Capability Gallery",
        "==================",
        "",
        *_render_note_block(),
        (
            "This section groups a small set of static, versioned illustrations that explain what "
            "HydroModPy can do without requiring notebook execution during the documentation build."
        ),
        "",
        ".. grid:: 1 1 2 3",
        "   :gutter: 2 2 3 3",
        "",
    ]
    for category_slug in ("mesh", "validation", "geographic"):
        category = CATEGORY_SPECS[category_slug]
        lines.extend(
            _render_grid_card(
                link=category.slug,
                title=category.title,
                deck=category.deck,
            )
        )
    lines.extend(
        [
            ".. toctree::",
            "   :hidden:",
            "   :maxdepth: 1",
            "",
        ]
    )
    for category_slug in ("mesh", "validation", "geographic"):
        if cases_by_category.get(category_slug):
            lines.append(f"   {category_slug}")
    return "\n".join(lines)


def _build_category_page(category_slug: str, cases: list[dict[str, Any]]) -> str:
    category = CATEGORY_SPECS[category_slug]
    lines = [
        AUTO_GENERATED_COMMENT,
        "",
        category.title,
        "=" * len(category.title),
        "",
        *_render_note_block(),
        category.intro,
        "",
        ".. grid:: 1 1 2 2",
        "   :gutter: 2 2 3 3",
        "",
    ]
    for case in cases:
        lines.extend(
            _render_grid_card(
                link=case["docname"],
                title=case["title"],
                deck=case["deck"],
            )
        )
    lines.extend(
        [
            ".. toctree::",
            "   :hidden:",
            "   :maxdepth: 1",
            "",
        ]
    )
    for case in cases:
        lines.append(f"   {case['docname']}")
    return "\n".join(lines)


def _build_case_page(case: dict[str, Any]) -> str:
    title = str(case["title"])
    lines = [
        AUTO_GENERATED_COMMENT,
        "",
        title,
        "=" * len(title),
        "",
        *_render_note_block(),
        str(case["summary"]),
        "",
    ]
    for image in case["images"]:
        lines.extend(
            [
                f".. figure:: {image['doc_path']}",
                f"   :alt: {image['alt_text']}",
                "   :width: 100%",
                "",
                f"   {image['caption']}",
                "",
            ]
        )

    lines.extend(
        [
            "What It Shows",
            "-------------",
            "",
        ]
    )
    for bullet in case["what_it_shows"]:
        lines.append(f"- {bullet}")
    lines.append("")

    if case["metrics"]:
        lines.extend(
            [
                "Key Metrics",
                "-----------",
                "",
            ]
        )
        for metric in case["metrics"]:
            lines.append(f"- {metric['label']}: {metric['display']}")
        lines.append("")

    lines.extend(
        [
            "Reproduce",
            "---------",
            "",
            "Run the underlying example or validation case with:",
            "",
            ".. code-block:: bash",
            "",
            f"   {case['reproduction_command']}",
            "",
            "Refresh the committed gallery artifacts with:",
            "",
            ".. code-block:: bash",
            "",
            f"   {case['gallery_update_command']}",
            "",
            "Source Pointers",
            "---------------",
            "",
        ]
    )
    for source_path in case["source_paths"]:
        lines.append(f"- ``{source_path}``")
    lines.append("")

    lines.extend(
        [
            "Artifacts",
            "---------",
            "",
        ]
    )
    for image_path in case["artifacts"]["image_repo_paths"]:
        lines.append(f"- ``{image_path}``")
    lines.append(
        "- ``{}`` stores the displayed metrics plus source hashes used by "
        "``python -m tools.doc_gallery --check``.".format(
            case["artifacts"]["summary_json_repo_path"]
        )
    )
    lines.append("")
    return "\n".join(lines)


def _collect_generated_files(source_root: Path) -> dict[str, Path]:
    collected: dict[str, Path] = {}
    for relative_dir in (
        Path("capability_gallery"),
        Path("_static") / "capability_gallery",
    ):
        target_dir = source_root / relative_dir
        if not target_dir.exists():
            continue
        for path in sorted(target_dir.rglob("*")):
            if path.is_file():
                collected[path.relative_to(source_root).as_posix()] = path
    return collected


def _compare_generated_trees(*, expected_source_root: Path, committed_source_root: Path) -> list[str]:
    expected_files = _collect_generated_files(expected_source_root)
    committed_files = _collect_generated_files(committed_source_root)
    issues: list[str] = []

    for relative_path in sorted(set(expected_files) - set(committed_files)):
        issues.append(f"Missing generated file: {relative_path}")
    for relative_path in sorted(set(committed_files) - set(expected_files)):
        issues.append(f"Unexpected generated file: {relative_path}")

    for relative_path in sorted(set(expected_files) & set(committed_files)):
        suffix = Path(relative_path).suffix.lower()
        if suffix not in TEXTUAL_SUFFIXES:
            continue
        if expected_files[relative_path].read_bytes() != committed_files[relative_path].read_bytes():
            issues.append(f"Stale generated file: {relative_path}")

    return issues


def generate_gallery(*, source_root: Path) -> None:
    """Generate the full gallery under one docs source tree."""

    _reset_generated_dirs(source_root)
    specs = build_gallery_specs()
    case_summaries = [_generate_case(spec, source_root) for spec in specs]
    summaries_by_category: dict[str, list[dict[str, Any]]] = {}
    for category_slug in CATEGORY_SPECS:
        summaries_by_category[category_slug] = [
            summary for summary in case_summaries if summary["category"] == category_slug
        ]

    docs_dir = source_root / "capability_gallery"
    static_dir = source_root / "_static" / "capability_gallery"
    case_dir = docs_dir / "cases"
    case_dir.mkdir(parents=True, exist_ok=True)

    for case in case_summaries:
        summary_path = static_dir / str(case["category"]) / f"{case['slug']}_summary.json"
        _write_json(summary_path, case)
        _write_text(case_dir / f"{case['slug']}.rst", _build_case_page(case))

    _write_text(docs_dir / "index.rst", _build_index_page(summaries_by_category))
    for category_slug, cases in summaries_by_category.items():
        if cases:
            _write_text(docs_dir / f"{category_slug}.rst", _build_category_page(category_slug, cases))


def main(argv: list[str] | None = None) -> int:
    """Entry point for ``python -m tools.doc_gallery``."""

    args = build_parser().parse_args(argv)
    if args.check:
        with tempfile.TemporaryDirectory(prefix="hydromodpy_doc_gallery_") as temp_dir:
            temp_source_root = Path(temp_dir) / "source"
            temp_source_root.mkdir(parents=True, exist_ok=True)
            generate_gallery(source_root=temp_source_root)
            issues = _compare_generated_trees(
                expected_source_root=temp_source_root,
                committed_source_root=DOCS_SOURCE_DIR,
            )
            if issues:
                print("Capability gallery is out of date. Regenerate it with:")
                print("  python -m tools.doc_gallery")
                for issue in issues:
                    print(f"- {issue}")
                return 1
        print("Capability gallery is in sync.")
        return 0

    generate_gallery(source_root=DOCS_SOURCE_DIR)
    print("Capability gallery refreshed under docs/readthedocs/source/.")
    return 0


__all__ = [
    "build_parser",
    "generate_gallery",
    "main",
]
