"""Generate the static illustrated capability gallery used by the docs."""

from __future__ import annotations

import argparse
import gc
import hashlib
import importlib
import json
import os
import stat
import time
from dataclasses import replace
from pathlib import Path
import shutil
import tempfile
from typing import Any

import numpy as np

from tools.mesh_bundle_viewer.runner.visualization_runner import (
    load_toml_config,
    run_visualization,
)

from .mesh_case_registry import (
    MESH_GALLERY_SCALE_ORDER,
    MESH_GALLERY_VARIANT_SPECS,
    scale_label as mesh_scale_label,
)
from .gallery_manifest import (
    CATEGORY_SPECS,
    GalleryCaseSpec,
    build_gallery_specs,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_SOURCE_DIR = REPO_ROOT / "docs" / "readthedocs" / "source"
VALIDATION_REPORT_DIR = REPO_ROOT / "validation_cases" / "reports" / "latest"
TEXTUAL_SUFFIXES = {".json", ".rst"}
AUTO_GENERATED_COMMENT = ".. This file is auto-generated by ``python -m tools.doc_gallery``."
AUTO_GENERATED_NOTE = (
    "This page and its static assets are auto-generated by ``python -m tools.doc_gallery``. "
    "The Sphinx build only reads committed PNG and JSON artifacts."
)
VALIDATION_SOLVER_LABELS = {
    "modflownwt": "MODFLOW-NWT",
    "modflow6": "MODFLOW 6",
    "boussinesq": "Boussinesq",
}
VALIDATION_SOLVER_ORDER = ("modflownwt", "modflow6", "boussinesq")


def _render_mesh_coverage_matrix(cases: list[dict[str, Any]]) -> list[str]:
    """Render one compact scale/variant coverage matrix for versioned mesh cases."""

    coverage: dict[tuple[str, str], list[str]] = {}
    for case in cases:
        metadata = dict(case.get("metadata", {}))
        scale = str(metadata.get("scale", "")).strip()
        variant = str(metadata.get("variant", "")).strip()
        outlet_id = str(metadata.get("outlet_id", "")).strip()
        if scale == "" or variant == "":
            continue
        coverage.setdefault((scale, variant), [])
        if outlet_id:
            coverage[(scale, variant)].append(outlet_id)

    lines = [
        "Coverage Matrix",
        "---------------",
        "",
        ".. list-table::",
        "   :header-rows: 1",
        "",
        "   * - Scale",
    ]
    for variant in MESH_GALLERY_VARIANT_SPECS.values():
        lines.append(f"     - {variant['label']}")

    for scale in MESH_GALLERY_SCALE_ORDER:
        lines.append(f"   * - {mesh_scale_label(scale)}")
        for variant in MESH_GALLERY_VARIANT_SPECS:
            outlet_ids = coverage.get((scale, variant), [])
            if outlet_ids:
                outlet_suffix = ", ".join(f"outlet {item}" for item in sorted(outlet_ids))
                cell_value = f"Versioned ({outlet_suffix})"
            else:
                cell_value = "Missing"
            lines.append(f"     - {cell_value}")
    lines.append("")
    return lines


def _render_mesh_family_matrix(cases: list[dict[str, Any]]) -> list[str]:
    """Render one compact family/outlet matrix when repeated mesh families are declared."""

    families: dict[str, dict[str, Any]] = {}
    for case in cases:
        metadata = dict(case.get("metadata", {}))
        family_key = str(metadata.get("case_family_key", "")).strip()
        family_label = str(metadata.get("case_family_label", "")).strip()
        if family_key == "" or family_label == "":
            continue
        entry = families.setdefault(
            family_key,
            {
                "label": family_label,
                "order": int(metadata.get("case_family_order", 999)),
                "scale_label": str(metadata.get("scale_label", metadata.get("scale", ""))).strip(),
                "variant_label": str(metadata.get("variant_label", metadata.get("variant", ""))).strip(),
                "outlet_ids": [],
            },
        )
        outlet_id = str(metadata.get("outlet_id", "")).strip()
        if outlet_id != "":
            entry["outlet_ids"].append(outlet_id)

    if not families:
        return []

    lines = [
        "Family Coverage",
        "---------------",
        "",
        ".. list-table::",
        "   :header-rows: 1",
        "",
        "   * - Case family",
        "     - Scale",
        "     - Variant",
        "     - Imported outlets",
    ]
    for family in sorted(
        families.values(),
        key=lambda item: (int(item["order"]), str(item["label"])),
    ):
        ordered_outlets = sorted(
            set(str(item) for item in family["outlet_ids"]),
            key=lambda item: int(item) if str(item).isdigit() else str(item),
        )
        lines.extend(
            [
                f"   * - {family['label']}",
                f"     - {family['scale_label']}",
                f"     - {family['variant_label']}",
                f"     - {', '.join(f'outlet {item}' for item in ordered_outlets)}",
            ]
        )
    lines.append("")
    return lines


def build_parser() -> argparse.ArgumentParser:
    """Build the public command-line parser."""

    parser = argparse.ArgumentParser(
        description=(
            "Generate or verify the static illustrated capability gallery used in the docs."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Regenerate the gallery in a temporary directory and verify that the committed "
            "text artifacts are in sync. PNG presence is checked, while staleness is tracked "
            "through source hashes stored in the generated JSON summaries."
        ),
    )
    return parser


def _repo_path(relative_path: str) -> Path:
    return (REPO_ROOT / Path(relative_path)).resolve()


def _repo_relative(path: str | Path) -> str:
    path_obj = Path(path).resolve() if not isinstance(path, Path) else path.resolve()
    try:
        return path_obj.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path_obj.as_posix()


def _docs_relative_static_path(*parts: str) -> str:
    return (Path("_static") / "capability_gallery" / Path(*parts)).as_posix()


def _repo_docs_artifact_path(*parts: str) -> str:
    return (Path("docs") / "readthedocs" / "source" / "_static" / "capability_gallery" / Path(*parts)).as_posix()


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _json_ready(value: Any) -> Any:
    if isinstance(value, Path):
        return _repo_relative(value)
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, dict):
        return {str(key): _json_ready(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_json_ready(item) for item in value]
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return str(value)


def _build_source_hashes(source_paths: tuple[str, ...]) -> dict[str, str]:
    hashes: dict[str, str] = {}
    for relative_path in source_paths:
        hashes[relative_path] = _sha256(_repo_path(relative_path))
    return hashes


def _import_symbol(import_path: str):
    module_name, symbol_name = import_path.split(":", 1)
    module = importlib.import_module(module_name)
    return getattr(module, symbol_name)


def _rmtree_onerror(func, path, exc_info) -> None:
    """Retry one failed ``rmtree`` step after clearing a read-only bit."""

    del exc_info
    os.chmod(path, stat.S_IWRITE)
    func(path)


def _remove_tree_with_retry(
    path: Path,
    *,
    retries: int = 12,
    base_delay_s: float = 0.5,
) -> None:
    """Remove one generated directory with retries for transient Windows locks."""

    if not path.exists():
        return

    last_error: PermissionError | None = None
    for attempt in range(retries):
        try:
            gc.collect()
            shutil.rmtree(path, onerror=_rmtree_onerror)
            return
        except FileNotFoundError:
            return
        except PermissionError as exc:
            last_error = exc
            gc.collect()
            if attempt == retries - 1:
                raise
            time.sleep(base_delay_s * (attempt + 1))

    if last_error is not None:
        raise last_error


def _reset_generated_dirs(source_root: Path) -> None:
    for relative_path in (
        Path("capability_gallery"),
        Path("_static") / "capability_gallery",
    ):
        target = source_root / relative_path
        if target.exists():
            _remove_tree_with_retry(target)
        target.mkdir(parents=True, exist_ok=True)


def _build_case_summary(
    spec: GalleryCaseSpec,
    *,
    metrics_source: dict[str, Any] | None,
    metadata: dict[str, Any],
    images_override: list[dict[str, Any]] | None = None,
    metrics_override: list[dict[str, Any]] | None = None,
    extra_summary: dict[str, Any] | None = None,
) -> dict[str, Any]:
    images = images_override
    if images is None:
        images = []
        for asset in spec.image_assets:
            static_doc_path = "/" + _docs_relative_static_path(spec.category, asset.filename)
            images.append(
                {
                    "filename": asset.filename,
                    "caption": asset.caption,
                    "alt_text": asset.alt_text,
                    "doc_path": static_doc_path,
                    "repo_path": _repo_docs_artifact_path(spec.category, asset.filename),
                }
            )

    summary_json_doc_path = "/" + _docs_relative_static_path(spec.category, f"{spec.slug}_summary.json")
    summary_json_repo_path = _repo_docs_artifact_path(spec.category, f"{spec.slug}_summary.json")

    metrics = metrics_override
    if metrics is None:
        metrics = []
        for metric_spec in spec.metric_specs:
            if metrics_source is None:
                raise ValueError("metrics_source is required when metrics_override is not provided.")
            raw_value = metrics_source[metric_spec.key]
            metrics.append(
                {
                    "label": metric_spec.label,
                    "key": metric_spec.key,
                    "value": _json_ready(raw_value),
                    "display": metric_spec.formatter(raw_value),
                }
            )

    summary = {
        "summary_schema_version": "capability_gallery_case_v1",
        "slug": spec.slug,
        "title": spec.title,
        "category": spec.category,
        "deck": spec.deck,
        "summary": spec.summary,
        "case_setup": list(spec.case_setup),
        "what_it_shows": list(spec.what_it_shows),
        "reference_highlights": list(spec.reference_highlights),
        "equations_rst": list(spec.equations_rst),
        "reproduction_command": spec.reproduction_command,
        "gallery_update_command": "python -m tools.doc_gallery",
        "source_paths": list(spec.source_paths),
        "source_hashes": _build_source_hashes(spec.source_paths),
        "docname": f"cases/{spec.slug}",
        "images": images,
        "metrics": metrics,
        "metadata": _json_ready(metadata),
        "artifacts": {
            "summary_json_doc_path": summary_json_doc_path,
            "summary_json_repo_path": summary_json_repo_path,
            "image_repo_paths": [image["repo_path"] for image in images],
        },
    }
    if extra_summary:
        summary.update(_json_ready(extra_summary))
    return summary


def _generate_mesh_viewer_case(spec: GalleryCaseSpec, source_root: Path) -> dict[str, Any]:
    preferred_assets = [asset for asset in spec.image_assets if asset.source_path is not None]
    if preferred_assets:
        with tempfile.TemporaryDirectory(prefix="hydromodpy_doc_gallery_mesh_viewer_") as temp_dir:
            temp_figure_path = Path(temp_dir) / spec.image_assets[0].filename
            config = load_toml_config(_repo_path(str(spec.metadata["config_path"])))
            config = replace(
                config,
                figure_output_path=temp_figure_path.resolve(),
                summary_output_path=None,
                show_window=False,
            )
            raw_summary = run_visualization(config)
        for asset in preferred_assets:
            destination = source_root / _docs_relative_static_path(spec.category, asset.filename)
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(_repo_path(str(asset.source_path)), destination)
    else:
        figure_path = source_root / _docs_relative_static_path(spec.category, spec.image_assets[0].filename)
        config = load_toml_config(_repo_path(str(spec.metadata["config_path"])))
        config = replace(
            config,
            figure_output_path=figure_path.resolve(),
            summary_output_path=None,
            show_window=False,
        )
        raw_summary = run_visualization(config)
    sanitized_viewer_summary = {
        key: _json_ready(value)
        for key, value in raw_summary.items()
        if key not in {"figure_output_path", "summary_output_path"}
    }
    if "bundle_dir" in raw_summary:
        sanitized_viewer_summary["bundle_dir"] = _repo_relative(str(raw_summary["bundle_dir"]))
    if "mesh_file" in raw_summary:
        sanitized_viewer_summary["mesh_file"] = _repo_relative(str(raw_summary["mesh_file"]))

    return _build_case_summary(
        spec,
        metrics_source={metric.key: raw_summary[metric.key] for metric in spec.metric_specs},
        metadata={
            **dict(spec.metadata),
            "config_path": str(spec.metadata["config_path"]),
            "viewer_summary": sanitized_viewer_summary,
        },
    )


def _generate_copy_assets_case(spec: GalleryCaseSpec, source_root: Path) -> dict[str, Any]:
    copied_assets = []
    for asset in spec.image_assets:
        if asset.source_path is None:
            raise ValueError(f"Gallery asset {asset.filename} is missing source_path.")
        destination = source_root / _docs_relative_static_path(spec.category, asset.filename)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(_repo_path(asset.source_path), destination)
        copied_assets.append(
            {
                "source_path": asset.source_path,
                "copied_to": _repo_docs_artifact_path(spec.category, asset.filename),
            }
        )

    return _build_case_summary(
        spec,
        metrics_source={},
        metadata={
            **dict(spec.metadata),
            "copied_assets": copied_assets,
        },
    )


def _build_validation_image_summary(
    *,
    category: str,
    filename: str,
    caption: str,
    alt_text: str,
) -> dict[str, Any]:
    return {
        "filename": filename,
        "caption": caption,
        "alt_text": alt_text,
        "doc_path": "/" + _docs_relative_static_path(category, filename),
        "repo_path": _repo_docs_artifact_path(category, filename),
    }


def _build_validation_solver_command(*, run_case_module: str, solver: str, include_solver_flag: bool) -> str:
    command = f"python -m {run_case_module} --no-show"
    if include_solver_flag:
        command += f" --solver {solver}"
    return command


def _generate_validation_case(spec: GalleryCaseSpec, source_root: Path) -> dict[str, Any]:
    run_case_module = importlib.import_module(str(spec.metadata["run_case_module"]))
    comparison_runner = getattr(run_case_module, str(spec.metadata["comparison_function_name"]))
    plotting_function = getattr(run_case_module, str(spec.metadata["plotting_function_name"]))
    metric_builder = getattr(run_case_module, str(spec.metadata["metric_builder_name"]))
    caller_file = _repo_path(str(spec.metadata["run_case_file"]))

    solver_variants = tuple(str(item) for item in spec.metadata.get("solver_variants", ()))
    default_solver = str(spec.metadata.get("default_solver", solver_variants[0] if solver_variants else ""))
    solver_details = {
        str(key): value for key, value in dict(spec.metadata.get("solver_details", {})).items()
    }
    include_solver_flag = len(solver_variants) > 1

    solver_runs: list[dict[str, Any]] = []
    all_image_repo_paths: list[str] = []
    default_images: list[dict[str, Any]] = []

    for solver in solver_variants:
        detail = dict(solver_details.get(solver, {}))
        filename = f"{spec.slug}__{solver}.png"
        figure_path = source_root / _docs_relative_static_path(spec.category, filename)
        comparison = comparison_runner(
            caller_file=caller_file,
            timeout=int(spec.metadata.get("timeout", 1800)),
            solver=solver,
        )
        plotting_function(comparison, output_png=figure_path, show_plot=False)

        image_summary = _build_validation_image_summary(
            category=spec.category,
            filename=filename,
            caption=(
                f"{spec.title} rendered with {detail.get('display_name', solver)} for the analytical gallery."
            ),
            alt_text=f"{spec.title} validation figure for {detail.get('display_name', solver)}",
        )
        all_image_repo_paths.append(image_summary["repo_path"])
        if solver == default_solver:
            default_images = [image_summary]

        solver_metadata = {
            "observable_name": getattr(comparison, "observable_name", None),
            "case_metadata": getattr(comparison, "metadata", {}),
            "tolerances": getattr(comparison, "tolerances", {}),
        }
        if hasattr(comparison, "solver"):
            solver_metadata["comparison_solver"] = getattr(comparison, "solver")
        if hasattr(comparison, "timestep"):
            solver_metadata["timestep"] = getattr(comparison, "timestep")
        if hasattr(comparison, "final_elapsed_days"):
            solver_metadata["final_elapsed_days"] = getattr(comparison, "final_elapsed_days")

        solver_runs.append(
            {
                "solver": solver,
                "solver_display_name": detail.get("display_name", solver),
                "is_default": solver == default_solver,
                "config_path": detail.get("config_path"),
                "tolerance_path": detail.get("tolerance_path"),
                "expected_output": detail.get("expected_output"),
                "command": _build_validation_solver_command(
                    run_case_module=str(spec.metadata["run_case_module"]),
                    solver=solver,
                    include_solver_flag=include_solver_flag,
                ),
                "metric_lines": list(metric_builder(comparison)),
                "image": image_summary,
                "metadata": solver_metadata,
            }
        )

    if not default_images and solver_runs:
        default_images = [solver_runs[0]["image"]]

    return _build_case_summary(
        spec,
        metrics_source=None,
        metadata={
            "case_dir": str(spec.metadata["case_dir"]),
            "default_solver": default_solver,
            "solver_variants": list(solver_variants),
            "solver_details": solver_details,
            "regime": spec.metadata.get("regime"),
            "dimension": spec.metadata.get("dimension"),
            "inventory_reference": spec.metadata.get("inventory_reference"),
            "case_sheet": spec.metadata.get("case_sheet", {}),
        },
        images_override=default_images,
        metrics_override=[],
        extra_summary={
            "solver_runs": solver_runs,
            "artifacts": {
                "summary_json_doc_path": "/" + _docs_relative_static_path(spec.category, f"{spec.slug}_summary.json"),
                "summary_json_repo_path": _repo_docs_artifact_path(spec.category, f"{spec.slug}_summary.json"),
                "image_repo_paths": all_image_repo_paths,
            },
        },
    )

def _generate_case(spec: GalleryCaseSpec, source_root: Path) -> dict[str, Any]:
    if spec.generator == "mesh_viewer":
        return _generate_mesh_viewer_case(spec, source_root)
    if spec.generator == "copy_assets":
        return _generate_copy_assets_case(spec, source_root)
    if spec.generator == "validation_case":
        return _generate_validation_case(spec, source_root)
    raise ValueError(f"Unsupported gallery generator kind: {spec.generator}")


def _render_note_block() -> list[str]:
    return [
        ".. note::",
        f"   {AUTO_GENERATED_NOTE}",
        "",
    ]


def _render_grid_card(*, link: str, title: str, deck: str) -> list[str]:
    return [
        "   .. grid-item-card::",
        "      :class-card: sd-shadow-sm sd-rounded-3 sd-p-4",
        f"      :link: {link}",
        "      :link-type: doc",
        "",
        f"      **{title}**",
        "      ^^^",
        f"      {deck}",
        "",
    ]


def _variant_rank(variant: str) -> int:
    for index, key in enumerate(MESH_GALLERY_VARIANT_SPECS):
        if key == variant:
            return index
    return len(MESH_GALLERY_VARIANT_SPECS)


def _mesh_case_sort_token(value: str) -> int | str:
    token = str(value).strip()
    return int(token) if token.isdigit() else token


def _group_mesh_cases_for_site_tabs(
    cases: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    grouped_candidates: dict[str, list[dict[str, Any]]] = {}
    standalone_cases: list[dict[str, Any]] = []

    for case in cases:
        metadata = dict(case.get("metadata", {}))
        group_key = str(metadata.get("site_tabs_group_key", "")).strip()
        if group_key == "":
            standalone_cases.append(case)
            continue
        grouped_candidates.setdefault(group_key, []).append(case)

    tabbed_groups: list[dict[str, Any]] = []
    for _, group_cases in sorted(
        grouped_candidates.items(),
        key=lambda item: (
            int(item[1][0].get("metadata", {}).get("case_family_order", 999)),
            str(item[1][0].get("metadata", {}).get("site_tabs_group_title", item[0])),
        ),
    ):
        ordered_cases = sorted(
            group_cases,
            key=lambda case: (
                int(case.get("metadata", {}).get("site_tabs_order", 999)),
                _mesh_case_sort_token(str(case.get("metadata", {}).get("outlet_id", ""))),
                str(case.get("title", "")),
            ),
        )
        if len(ordered_cases) > 1:
            metadata = dict(ordered_cases[0].get("metadata", {}))
            tabbed_groups.append(
                {
                    "title": str(
                        metadata.get(
                            "site_tabs_group_title",
                            metadata.get("case_family_label", "Repeated Sites"),
                        )
                    ),
                    "cases": ordered_cases,
                }
            )
        else:
            standalone_cases.extend(ordered_cases)
    return standalone_cases, tabbed_groups


def _group_mesh_cases_for_tabs(
    cases: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    grouped_candidates: dict[tuple[str, str], list[dict[str, Any]]] = {}
    standalone_cases: list[dict[str, Any]] = []

    for case in cases:
        metadata = dict(case.get("metadata", {}))
        scale = str(metadata.get("scale", "")).strip()
        outlet_id = str(metadata.get("outlet_id", "")).strip()
        if scale == "" or outlet_id == "":
            standalone_cases.append(case)
            continue
        grouped_candidates.setdefault((scale, outlet_id), []).append(case)

    scale_rank = {scale: index for index, scale in enumerate(MESH_GALLERY_SCALE_ORDER)}
    tabbed_groups: list[dict[str, Any]] = []
    for (scale, outlet_id), group_cases in sorted(
        grouped_candidates.items(),
        key=lambda item: (
            scale_rank.get(item[0][0], 999),
            int(item[0][1]) if item[0][1].isdigit() else item[0][1],
        ),
    ):
        ordered_cases = sorted(
            group_cases,
            key=lambda case: _variant_rank(str(case.get("metadata", {}).get("variant", ""))),
        )
        if len(ordered_cases) > 1:
            metadata = dict(ordered_cases[0].get("metadata", {}))
            tabbed_groups.append(
                {
                    "title": str(
                        metadata.get(
                            "comparison_group_title",
                            f"{metadata.get('scale_label', scale)}, outlet {outlet_id}",
                        )
                    ),
                    "cases": ordered_cases,
                }
            )
        else:
            standalone_cases.extend(ordered_cases)
    return standalone_cases, tabbed_groups


def _build_index_page(cases_by_category: dict[str, list[dict[str, Any]]]) -> str:
    lines = [
        AUTO_GENERATED_COMMENT,
        "",
        "Capability Gallery",
        "==================",
        "",
        *_render_note_block(),
        (
            "This section groups a small set of static, versioned illustrations that explain what "
            "HydroModPy can do without requiring notebook execution during the documentation build."
        ),
        "",
        ".. grid:: 1 1 2 3",
        "   :gutter: 2 2 3 3",
        "",
    ]
    for category_slug in ("mesh", "validation", "geographic"):
        category = CATEGORY_SPECS[category_slug]
        lines.extend(
            _render_grid_card(
                link=category.slug,
                title=category.title,
                deck=category.deck,
            )
        )
    lines.extend(
        [
            ".. toctree::",
            "   :hidden:",
            "   :maxdepth: 1",
            "",
        ]
    )
    for category_slug in ("mesh", "validation", "geographic"):
        if cases_by_category.get(category_slug):
            lines.append(f"   {category_slug}")
    return "\n".join(lines)


def _build_category_page(category_slug: str, cases: list[dict[str, Any]]) -> str:
    category = CATEGORY_SPECS[category_slug]
    all_cases = list(cases)
    lines = [
        AUTO_GENERATED_COMMENT,
        "",
        category.title,
        "=" * len(category.title),
        "",
        *_render_note_block(),
        category.intro,
        "",
    ]

    if category_slug == "mesh":
        imported_scale_labels = sorted(
            {
                str(case.get("metadata", {}).get("scale_label", case.get("metadata", {}).get("scale", ""))).strip()
                for case in cases
                if str(case.get("metadata", {}).get("scale", "")).strip()
            }
        )
        present_variants = sorted(
            {
                str(case.get("metadata", {}).get("variant_label", case.get("metadata", {}).get("variant", ""))).strip()
                for case in cases
                if str(case.get("metadata", {}).get("variant", "")).strip()
            }
        )
        imported_case_family_labels = sorted(
            {
                str(case.get("metadata", {}).get("case_family_label", "")).strip()
                for case in cases
                if str(case.get("metadata", {}).get("case_family_label", "")).strip()
            }
        )
        missing_scale_labels = [
            scale_label
            for scale_label in ("10 km2", "100 km2", "1000 km2")
            if scale_label not in imported_scale_labels
        ]
        lines.extend(
            [
                "Current Coverage",
                "----------------",
                "",
                "- Imported case families: "
                + (", ".join(imported_case_family_labels) if imported_case_family_labels else "none yet")
                + ".",
                "- Imported scales: " + (", ".join(imported_scale_labels) if imported_scale_labels else "none yet") + ".",
                "- Present variants: " + (", ".join(present_variants) if present_variants else "none yet") + ".",
                "- Prepared but not yet versioned: " + (", ".join(missing_scale_labels) if missing_scale_labels else "none") + ".",
                "",
            ]
        )
        family_matrix = _render_mesh_family_matrix(cases)
        lines.extend(family_matrix if family_matrix else _render_mesh_coverage_matrix(cases))
        standalone_cases, site_tab_groups = _group_mesh_cases_for_site_tabs(cases)
        if site_tab_groups:
            lines.extend(
                [
                    "Repeated Sites",
                    "--------------",
                    "",
                    "These tab sets group one repeated mesh family across several outlets imported from the batch runs.",
                    "",
                ]
            )
            for group in site_tab_groups:
                title = str(group["title"])
                lines.extend(
                    [
                        title,
                        "~" * len(title),
                        "",
                        ".. tab-set::",
                        "",
                    ]
                )
                for case in group["cases"]:
                    tab_label = str(
                        case.get("metadata", {}).get(
                            "site_tabs_label",
                            f"Outlet {case.get('metadata', {}).get('outlet_id', '')}",
                        )
                    ).strip()
                    lines.extend(
                        [
                            f"   .. tab-item:: {tab_label}",
                            "",
                        ]
                    )
                    images = list(case.get("images", []))
                    _append_mesh_tab_images(lines, images, indent="      ")
                    lines.extend(
                        [
                            f"      **{case['title']}**",
                            "",
                            f"      {case['deck']}",
                            "",
                        ]
                    )
                    outlet_id = str(case.get("metadata", {}).get("outlet_id", "")).strip()
                    if outlet_id:
                        lines.append(f"      - Outlet: ``{outlet_id}``")
                    constraints_mode = str(case.get("metadata", {}).get("constraints_mode", "")).strip()
                    if constraints_mode:
                        lines.append(f"      - Constraints mode: ``{constraints_mode}``")
                    for metric in list(case.get("metrics", []))[:4]:
                        lines.append(f"      - {metric['label']}: {metric['display']}")
                    lines.extend(
                        [
                            "",
                            f"      See :doc:`the full case page <{case['docname']}>`.",
                            "",
                        ]
                    )

        standalone_cases, tabbed_groups = _group_mesh_cases_for_tabs(standalone_cases)
        if tabbed_groups:
            lines.extend(
                [
                    "Comparable Variants",
                    "-------------------",
                    "",
                    "These tab sets group the same support and outlet across multiple meshing policies.",
                    "",
                ]
            )
            for group in tabbed_groups:
                title = str(group["title"])
                lines.extend(
                    [
                        title,
                        "~" * len(title),
                        "",
                        ".. tab-set::",
                        "",
                    ]
                )
                for case in group["cases"]:
                    variant_label = str(
                        case.get("metadata", {}).get("variant_label", case.get("title", "Variant"))
                    )
                    lines.extend(
                        [
                            f"   .. tab-item:: {variant_label}",
                            "",
                        ]
                    )
                    images = list(case.get("images", []))
                    _append_mesh_tab_images(lines, images, indent="      ")
                    lines.extend(
                        [
                            f"      **{case['title']}**",
                            "",
                            f"      {case['deck']}",
                            "",
                        ]
                    )
                    constraints_mode = str(case.get("metadata", {}).get("constraints_mode", "")).strip()
                    if constraints_mode:
                        lines.append(f"      - Constraints mode: ``{constraints_mode}``")
                    for metric in list(case.get("metrics", []))[:4]:
                        lines.append(f"      - {metric['label']}: {metric['display']}")
                    lines.extend(
                        [
                            "",
                            f"      See :doc:`the full case page <{case['docname']}>`.",
                            "",
                        ]
                    )
        cases = standalone_cases
    elif category_slug == "validation":
        solver_counts = {
            solver: sum(
                1
                for case in cases
                if solver in tuple(case.get("metadata", {}).get("solver_variants", ()))
            )
            for solver in VALIDATION_SOLVER_ORDER
        }
        batch_reports = _load_validation_batch_reports()
        lines.extend(
            [
                "Current Coverage",
                "----------------",
                "",
                "- Solver variants discovered: "
                + ", ".join(
                    f"{VALIDATION_SOLVER_LABELS.get(solver, solver)} ({solver_counts[solver]})"
                    for solver in VALIDATION_SOLVER_ORDER
                    if solver_counts[solver] > 0
                )
                + ".",
                "",
                "Latest Batch Reports",
                "--------------------",
                "",
            ]
        )
        if batch_reports:
            for report in batch_reports:
                solver = str(report.get("solver", "")).strip().lower()
                generated_at = str(report.get("generated_at_utc", "")).strip()
                completed = int(report.get("completed_case_count", 0))
                selected = int(report.get("selected_case_count", 0))
                duration_seconds = float(report.get("total_duration_seconds", 0.0))
                all_passed = bool(report.get("all_passed", False))
                status = "passed" if all_passed else "failed"
                lines.append(
                    "- "
                    + f"{VALIDATION_SOLVER_LABELS.get(solver, solver)}: "
                    + f"{completed}/{selected} cases {status} on {generated_at} "
                    + f"({duration_seconds:.1f} s), report ``{report['_report_repo_path']}``."
                )
        else:
            lines.append("- No committed validation batch reports yet.")
        lines.append("")

    if cases:
        lines.extend(
            [
            ".. grid:: 1 1 2 2",
            "   :gutter: 2 2 3 3",
            "",
            ]
        )
        for case in cases:
            lines.extend(
                _render_grid_card(
                    link=case["docname"],
                    title=case["title"],
                    deck=case["deck"],
                )
            )
    lines.extend(
        [
            ".. toctree::",
            "   :hidden:",
            "   :maxdepth: 1",
            "",
        ]
    )
    for case in all_cases:
            lines.append(f"   {case['docname']}")
    return "\n".join(lines)


def _append_figure(
    lines: list[str],
    image: dict[str, Any],
    *,
    indent: str = "",
    width: str = "100%",
) -> None:
    lines.extend(
        [
            f"{indent}.. figure:: {image['doc_path']}",
            f"{indent}   :alt: {image['alt_text']}",
            f"{indent}   :width: {width}",
            "",
            f"{indent}   {image['caption']}",
            "",
        ]
    )


def _append_mesh_tab_images(
    lines: list[str],
    images: list[dict[str, Any]],
    *,
    indent: str = "",
) -> None:
    if not images:
        return
    _append_figure(lines, images[0], indent=indent, width="85%")
    if len(images) > 1:
        _append_figure(lines, images[1], indent=indent, width="35%")


def _render_validation_solver_block(run: dict[str, Any], *, indent: str = "") -> list[str]:
    lines: list[str] = []
    image = run.get("image")
    if image:
        _append_figure(lines, image, indent=indent)

    if run.get("metric_lines"):
        lines.append(f"{indent}**Metrics**")
        for metric_line in run["metric_lines"]:
            lines.append(f"{indent}- {metric_line}")
        lines.append("")

    details: list[str] = []
    if run.get("config_path"):
        details.append(f"Config file: ``{run['config_path']}``")
    if run.get("tolerance_path"):
        details.append(f"Tolerances: ``{run['tolerance_path']}``")
    if run.get("expected_output"):
        details.append(str(run["expected_output"]))
    for item in details:
        lines.append(f"{indent}- {item}")
    if details:
        lines.append("")

    lines.extend(
        [
            f"{indent}.. code-block:: bash",
            "",
            f"{indent}   {run['command']}",
            "",
        ]
    )
    return lines


def _build_case_page(case: dict[str, Any]) -> str:
    title = str(case["title"])
    lines = [
        AUTO_GENERATED_COMMENT,
        "",
        title,
        "=" * len(title),
        "",
        *_render_note_block(),
        str(case["summary"]),
        "",
    ]
    solver_runs = list(case.get("solver_runs", []))
    if not solver_runs:
        for image in case["images"]:
            _append_figure(lines, image)

    if case["case_setup"]:
        lines.extend(
            [
                "Case Setup",
                "----------",
                "",
            ]
        )
        for bullet in case["case_setup"]:
            lines.append(f"- {bullet}")
        lines.append("")

    lines.extend(
        [
            "What It Shows",
            "-------------",
            "",
        ]
    )
    for bullet in case["what_it_shows"]:
        lines.append(f"- {bullet}")
    lines.append("")

    if case["metrics"]:
        lines.extend(
            [
                "Key Metrics",
                "-----------",
                "",
            ]
        )
        for metric in case["metrics"]:
            lines.append(f"- {metric['label']}: {metric['display']}")
        lines.append("")

    if case["reference_highlights"] or case["equations_rst"]:
        lines.extend(
            [
                "Analytical Reference",
                "--------------------",
                "",
            ]
        )
        for bullet in case["reference_highlights"]:
            lines.append(f"- {bullet}")
        if case["reference_highlights"] and case["equations_rst"]:
            lines.append("")
        for equation in case["equations_rst"]:
            lines.extend(
                [
                    ".. math::",
                    "",
                    f"   {equation}",
                    "",
                ]
            )
        if lines[-1] != "":
            lines.append("")

    if solver_runs:
        metadata = dict(case.get("metadata", {}))
        default_solver = metadata.get("default_solver")
        solver_display_names = [
            str(run.get("solver_display_name", run.get("solver", "")))
            for run in solver_runs
        ]
        lines.extend(
            [
                "Solver Coverage",
                "---------------",
                "",
            ]
        )
        if default_solver:
            default_label = next(
                (
                    run.get("solver_display_name", run.get("solver", ""))
                    for run in solver_runs
                    if run.get("solver") == default_solver
                ),
                default_solver,
            )
            lines.append(f"- Default solver: {default_label}")
        lines.append(f"- Available variants: {', '.join(solver_display_names)}")
        lines.append("")

        if len(solver_runs) > 1:
            lines.extend(
                [
                    ".. tab-set::",
                    "",
                ]
            )
            for run in solver_runs:
                lines.extend(
                    [
                        f"   .. tab-item:: {run['solver_display_name']}",
                        "",
                    ]
                )
                lines.extend(_render_validation_solver_block(run, indent="      "))
        else:
            lines.extend(_render_validation_solver_block(solver_runs[0]))

    lines.extend(
        [
            "Reproduce",
            "---------",
            "",
            "Run the underlying example or validation case with:",
            "",
            ".. code-block:: bash",
            "",
            f"   {case['reproduction_command']}",
            "",
            "Refresh the committed gallery artifacts with:",
            "",
            ".. code-block:: bash",
            "",
            f"   {case['gallery_update_command']}",
            "",
            "Source Pointers",
            "---------------",
            "",
        ]
    )
    for source_path in case["source_paths"]:
        lines.append(f"- ``{source_path}``")
    lines.append("")

    lines.extend(
        [
            "Artifacts",
            "---------",
            "",
        ]
    )
    for image_path in case["artifacts"]["image_repo_paths"]:
        lines.append(f"- ``{image_path}``")
    lines.append(
        "- ``{}`` stores the displayed metrics plus source hashes used by "
        "``python -m tools.doc_gallery --check``.".format(
            case["artifacts"]["summary_json_repo_path"]
        )
    )
    lines.append("")
    return "\n".join(lines)


def _collect_generated_files(source_root: Path) -> dict[str, Path]:
    collected: dict[str, Path] = {}
    for relative_dir in (
        Path("capability_gallery"),
        Path("_static") / "capability_gallery",
    ):
        target_dir = source_root / relative_dir
        if not target_dir.exists():
            continue
        for path in sorted(target_dir.rglob("*")):
            if path.is_file():
                collected[path.relative_to(source_root).as_posix()] = path
    return collected


def _compare_generated_trees(*, expected_source_root: Path, committed_source_root: Path) -> list[str]:
    expected_files = _collect_generated_files(expected_source_root)
    committed_files = _collect_generated_files(committed_source_root)
    issues: list[str] = []

    for relative_path in sorted(set(expected_files) - set(committed_files)):
        issues.append(f"Missing generated file: {relative_path}")
    for relative_path in sorted(set(committed_files) - set(expected_files)):
        issues.append(f"Unexpected generated file: {relative_path}")

    for relative_path in sorted(set(expected_files) & set(committed_files)):
        suffix = Path(relative_path).suffix.lower()
        if suffix not in TEXTUAL_SUFFIXES:
            continue
        if expected_files[relative_path].read_bytes() != committed_files[relative_path].read_bytes():
            issues.append(f"Stale generated file: {relative_path}")

    return issues


def _load_validation_batch_reports() -> list[dict[str, Any]]:
    reports: list[dict[str, Any]] = []
    if not VALIDATION_REPORT_DIR.exists():
        return reports

    for path in sorted(VALIDATION_REPORT_DIR.glob("*.json")):
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        if str(payload.get("schema_version", "")).strip() != "validation_batch_report_v1":
            continue
        payload["_report_repo_path"] = _repo_relative(path)
        reports.append(payload)

    solver_rank = {solver: index for index, solver in enumerate(VALIDATION_SOLVER_ORDER)}
    return sorted(
        reports,
        key=lambda payload: (
            solver_rank.get(str(payload.get("solver", "")).strip().lower(), 999),
            str(payload.get("_report_repo_path", "")),
        ),
    )


def generate_gallery(*, source_root: Path) -> None:
    """Generate the full gallery under one docs source tree."""

    _reset_generated_dirs(source_root)
    specs = build_gallery_specs()
    case_summaries = [_generate_case(spec, source_root) for spec in specs]
    summaries_by_category: dict[str, list[dict[str, Any]]] = {}
    for category_slug in CATEGORY_SPECS:
        summaries_by_category[category_slug] = [
            summary for summary in case_summaries if summary["category"] == category_slug
        ]

    docs_dir = source_root / "capability_gallery"
    static_dir = source_root / "_static" / "capability_gallery"
    case_dir = docs_dir / "cases"
    case_dir.mkdir(parents=True, exist_ok=True)

    for case in case_summaries:
        summary_path = static_dir / str(case["category"]) / f"{case['slug']}_summary.json"
        _write_json(summary_path, case)
        _write_text(case_dir / f"{case['slug']}.rst", _build_case_page(case))

    _write_text(docs_dir / "index.rst", _build_index_page(summaries_by_category))
    for category_slug, cases in summaries_by_category.items():
        if cases:
            _write_text(docs_dir / f"{category_slug}.rst", _build_category_page(category_slug, cases))


def main(argv: list[str] | None = None) -> int:
    """Entry point for ``python -m tools.doc_gallery``."""

    args = build_parser().parse_args(argv)
    if args.check:
        with tempfile.TemporaryDirectory(prefix="hydromodpy_doc_gallery_") as temp_dir:
            temp_source_root = Path(temp_dir) / "source"
            temp_source_root.mkdir(parents=True, exist_ok=True)
            generate_gallery(source_root=temp_source_root)
            issues = _compare_generated_trees(
                expected_source_root=temp_source_root,
                committed_source_root=DOCS_SOURCE_DIR,
            )
            if issues:
                print("Capability gallery is out of date. Regenerate it with:")
                print("  python -m tools.doc_gallery")
                for issue in issues:
                    print(f"- {issue}")
                return 1
        print("Capability gallery is in sync.")
        return 0

    generate_gallery(source_root=DOCS_SOURCE_DIR)
    print("Capability gallery refreshed under docs/readthedocs/source/.")
    return 0


__all__ = [
    "build_parser",
    "generate_gallery",
    "main",
]
