"""Generate the configuration reference RST tree for HydroModPy.

Outputs three layers under ``docs/source/user_guide/config_reference/``:

- ``index.rst`` (Couche 1): overview page with a grid card per top-level
  section.
- ``<section>.rst`` (Couche 2): one page per top-level section listing
  its direct fields and their type, default, description.
- ``complete_toml.rst`` (Couche 4): one page with the complete annotated
  TOML reference grouped by section, with collapsible dropdowns.

Couche 3 (interactive Stoplight viewer) is skipped per the v1 plan.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

from pydantic import BaseModel
from pydantic.fields import FieldInfo

from hydromodpy.config import HydroModPyConfig

REFERENCE_DIR = Path("docs/source/user_guide/config_reference")
DIAGRAM_DIR = REFERENCE_DIR / "_diagrams"
GALLERY_VALIDATION_DIR = Path("docs/source/_static/capability_gallery/validation")
GALLERY_CASES_DIR = "capability_gallery/cases"


def _scan_section_to_cases() -> dict[str, list[tuple[str, str]]]:
    """Map TOML section name to list of (slug, title) tuples that reference it."""
    out: dict[str, set[tuple[str, str]]] = defaultdict(set)
    if not GALLERY_VALIDATION_DIR.exists():
        return {k: sorted(v) for k, v in out.items()}
    for path in GALLERY_VALIDATION_DIR.glob("*_summary.json"):
        try:
            data = json.loads(path.read_text())
        except Exception:
            continue
        slug = data.get("slug") or path.stem.removesuffix("_summary")
        title = data.get("title", slug)
        seen_sections: set[str] = set()
        param_docs = data.get("parameter_docs", {})
        for bucket in ("reference_parameters", "common_setup"):
            for entry in param_docs.get(bucket, []) or []:
                field = entry.get("field", "")
                if "." in field:
                    seen_sections.add(field.split(".", 1)[0])
        for solver_overrides in (param_docs.get("solver_overrides") or {}).values():
            for entry in solver_overrides:
                field = entry.get("field", "")
                if "." in field:
                    seen_sections.add(field.split(".", 1)[0])
        for section in seen_sections:
            out[section].add((slug, title))
    return {k: sorted(v) for k, v in out.items()}


GENERATED_HEADER = (
    ".. AUTO-GENERATED by tools/doc_config. Do not edit by hand.\n"
    ".. Run ``python -m tools.doc_config`` to refresh.\n\n"
)


def _try_render_er_diagram(model: type, output_path: Path) -> Path | None:
    """Render an ER SVG for ``model``. Returns the path on success, None otherwise."""
    try:
        import erdantic
    except ImportError:
        return None
    try:
        diagram = erdantic.create(model)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        diagram.draw(out=str(output_path))
        return output_path
    except Exception:
        return None


def _unwrap(annotation: Any) -> Any:
    """Strip Annotated/Optional/Union wrappers and return the inner BaseModel."""
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation
    args = getattr(annotation, "__args__", ()) or ()
    for arg in args:
        if isinstance(arg, type) and issubclass(arg, BaseModel):
            return arg
    return annotation


def _format_default(field: FieldInfo) -> str:
    if field.is_required():
        return "required"
    if field.default_factory is not None:
        return "factory"
    default = field.default
    if isinstance(default, str):
        return f'"{default}"'
    return repr(default)


def _format_annotation(field: FieldInfo) -> str:
    annotation = field.annotation
    text = str(annotation)
    return text.replace("typing.", "").replace("hydromodpy.", "hmp.")


def _section_title(name: str) -> str:
    return name.replace("_", " ").title()


def _wrap_table_cell(text: str, width: int = 88) -> list[str]:
    """Wrap a list-table cell value across multiple indented lines."""
    import textwrap

    text = text.replace("\n", " ").strip()
    if not text:
        return ["     - "]
    pieces = textwrap.wrap(text, width=width) or [text]
    out = [f"     - {pieces[0]}"]
    for piece in pieces[1:]:
        out.append(f"       {piece}")
    return out


def _render_couche2(
    section_name: str,
    model: type[BaseModel],
    diagram_rel: str | None,
    gallery_cases: list[tuple[str, str]] | None = None,
) -> str:
    title = f"[{section_name}] {model.__name__}"
    lines = [
        GENERATED_HEADER,
        f"{title}",
        "=" * len(title),
        "",
        f"TOML section: ``[{section_name}]``",
        "",
        f"Pydantic model: ``{model.__name__}``",
        f"defined in ``{model.__module__}``.",
        "",
    ]
    docstring = (model.__doc__ or "").strip()
    if docstring:
        lines.extend([docstring, ""])

    if diagram_rel:
        lines.extend(
            [
                "Entity-relationship diagram",
                "---------------------------",
                "",
                f".. image:: {diagram_rel}",
                f"   :alt: ER diagram for {model.__name__}",
                "   :class: er-diagram",
                "",
            ]
        )

    lines.extend(
        [
            "Fields",
            "------",
            "",
            ".. list-table::",
            "   :header-rows: 1",
            "   :widths: 22 26 14 38",
            "",
            "   * - Field",
            "     - Type",
            "     - Default",
            "     - Description",
        ]
    )
    for field_name, field in model.model_fields.items():
        description = (field.description or "").replace("\n", " ").strip()
        lines.append(f"   * - ``{field_name}``")
        lines.append(f"     - ``{_format_annotation(field)}``")
        lines.append(f"     - ``{_format_default(field)}``")
        lines.extend(_wrap_table_cell(description or "*(no description)*"))
    lines.append("")

    if gallery_cases:
        lines.extend(
            [
                "Cases using this section",
                "------------------------",
                "",
                "Validation gallery cases that reference fields from this section:",
                "",
            ]
        )
        for slug, _title in gallery_cases:
            lines.append(f"- :doc:`/{GALLERY_CASES_DIR}/{slug}`")
        lines.append("")
    return "\n".join(lines)


def _render_couche1(top_fields: dict[str, FieldInfo]) -> str:
    lines = [
        GENERATED_HEADER,
        "Configuration overview",
        "======================",
        "",
        "Card-based map of every TOML section validated by ``HydroModPyConfig``.",
        "Click a card to open the section detail page.",
        "",
        "For the full annotated TOML reference, see :doc:`complete_toml`.",
        "",
        ".. grid:: 1 1 2 3",
        "   :gutter: 2 2 3 3",
        "",
    ]
    for name, field in top_fields.items():
        model = _unwrap(field.annotation)
        if not (isinstance(model, type) and issubclass(model, BaseModel)):
            continue
        description = (field.description or "").replace("\n", " ").strip()
        lines.extend(
            [
                "   .. grid-item-card::",
                f"      :link: {name}",
                "      :link-type: doc",
                "      :class-card: sd-shadow-sm sd-rounded-3 sd-p-3",
                "",
                f"      **[{name}]**",
                "      ^^^",
                f"      {description or _section_title(name)}",
                "",
            ]
        )
    lines.extend(
        [
            ".. toctree::",
            "   :hidden:",
            "",
            "   complete_toml",
        ]
    )
    for name, field in top_fields.items():
        model = _unwrap(field.annotation)
        if isinstance(model, type) and issubclass(model, BaseModel):
            lines.append(f"   {name}")
    lines.append("")
    return "\n".join(lines)


def _render_couche4(top_fields: dict[str, FieldInfo]) -> str:
    lines = [
        GENERATED_HEADER,
        "Complete annotated TOML reference",
        "=================================",
        "",
        "Every TOML section with its direct fields, defaults and types.",
        "Sub-models are linked back to their per-section page.",
        "Use this page as a copy-paste source for ``project.toml`` snippets.",
        "",
    ]
    for name, field in top_fields.items():
        model = _unwrap(field.annotation)
        if not (isinstance(model, type) and issubclass(model, BaseModel)):
            continue
        lines.append(f".. dropdown:: ``[{name}]`` ({model.__name__})")
        lines.append("   :icon: gear")
        lines.append("")
        lines.append(f"   See :doc:`{name}` for the full description.")
        lines.append("")
        lines.append("   .. code-block:: text")
        lines.append("")
        lines.append(f"      [{name}]")
        for field_name, sub_field in model.model_fields.items():
            description = (sub_field.description or "no description").replace("\n", " ").strip()
            default = _format_default(sub_field)
            lines.append(f"      # {description}")
            lines.append(f"      {field_name} = {default}")
        lines.append("")
    return "\n".join(lines)


def generate_all(output_dir: Path | None = None) -> list[Path]:
    """Render every generated RST file. Returns the paths that were written."""
    out = (output_dir or REFERENCE_DIR).resolve()
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    top_fields = HydroModPyConfig.model_fields

    index_path = out / "index.rst"
    index_path.write_text(_render_couche1(top_fields))
    written.append(index_path)

    complete_path = out / "complete_toml.rst"
    complete_path.write_text(_render_couche4(top_fields))
    written.append(complete_path)

    diagram_root = out / "_diagrams"
    diagram_root.mkdir(parents=True, exist_ok=True)
    section_cases = _scan_section_to_cases()

    for name, field in top_fields.items():
        model = _unwrap(field.annotation)
        if not (isinstance(model, type) and issubclass(model, BaseModel)):
            continue
        diagram_rel: str | None = None
        diagram_path = diagram_root / f"{name}.svg"
        rendered = _try_render_er_diagram(model, diagram_path)
        if rendered is not None:
            diagram_rel = f"_diagrams/{name}.svg"
            written.append(rendered)
        page_path = out / f"{name}.rst"
        page_path.write_text(_render_couche2(name, model, diagram_rel, section_cases.get(name, [])))
        written.append(page_path)

    return written


__all__ = ["generate_all"]
