"""Generate the configuration reference RST tree for HydroModPy.

Outputs five layers under ``docs/source/user_guide/config_reference/``:

- ``index.rst`` (Couche 1): overview page with a grid card per top-level
  section.
- ``<section>.rst`` (Couche 2): one page per top-level section listing
  its direct fields and their type, default, description, with a TOML
  starter snippet, GitHub source links, profile filtering and stability
  badges.
- ``schema_explorer.rst`` (Couche 3): interactive Stoplight Elements view
  of the JSON Schema exported from ``HydroModPyConfig``. The schema JSON
  is also written to ``docs/source/_static/hydromodpy-schema.json`` for
  external tools.
- ``complete_toml.rst`` (Couche 4): one page with the complete annotated
  TOML reference grouped by section, producing valid copy-pasteable TOML
  (required and factory fields are commented out with a placeholder).
- ``config_index.rst`` (Couche 5): flat global index of every TOML path
  with type, profile, page link and GitHub source link. Cible Ctrl+F.
"""

from __future__ import annotations

import contextlib
import html
import inspect
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

from pydantic import BaseModel
from pydantic.fields import FieldInfo

from hydromodpy.config import HydroModPyConfig
from hydromodpy.core.config_kit.introspect import extract_profile
from hydromodpy.core.config_kit.profile import Profile
from tools.doc_config.coverage import find_uncovered_opaque_fields

REPO_ROOT = Path(__file__).resolve().parents[2]
REFERENCE_DIR = Path("docs/source/user_guide/config_reference")
DIAGRAM_DIR = REFERENCE_DIR / "_diagrams"
GALLERY_VALIDATION_DIR = Path("docs/source/_static/capability_gallery/validation")
GALLERY_CASES_DIR = "capability_gallery/cases"
SCHEMA_OUTPUT = Path("docs/source/_static/hydromodpy-schema.json")
SEARCH_INDEX_OUTPUT = Path("docs/source/_static/hmp-config-search.json")

GITHUB_REPO = "HydroModPy/HydroModPy"
GITHUB_BRANCH = "master"

GENERATED_HEADER = (
    ".. AUTO-GENERATED by tools/doc_config. Do not edit by hand.\n"
    ".. Run ``python -m tools.doc_config`` to refresh.\n\n"
)

MAX_NESTED_DEPTH = 3


# ---------------------------------------------------------------------------
# Capability-gallery scan
# ---------------------------------------------------------------------------


def _scan_section_to_cases() -> dict[str, list[tuple[str, str]]]:
    """Map TOML section name to list of (slug, title) tuples that reference it."""
    out: dict[str, set[tuple[str, str]]] = defaultdict(set)
    if not GALLERY_VALIDATION_DIR.exists():
        return {k: sorted(v) for k, v in out.items()}
    for path in GALLERY_VALIDATION_DIR.glob("*_summary.json"):
        try:
            data = json.loads(path.read_text())
        except Exception:
            continue
        slug = data.get("slug") or path.stem.removesuffix("_summary")
        title = data.get("title", slug)
        seen_sections: set[str] = set()
        param_docs = data.get("parameter_docs", {})
        for bucket in ("reference_parameters", "common_setup"):
            for entry in param_docs.get(bucket, []) or []:
                field = entry.get("field", "")
                if "." in field:
                    seen_sections.add(field.split(".", 1)[0])
        for solver_overrides in (param_docs.get("solver_overrides") or {}).values():
            for entry in solver_overrides:
                field = entry.get("field", "")
                if "." in field:
                    seen_sections.add(field.split(".", 1)[0])
        for section in seen_sections:
            out[section].add((slug, title))
    return {k: sorted(v) for k, v in out.items()}


# ---------------------------------------------------------------------------
# ER diagram rendering
# ---------------------------------------------------------------------------


def _try_render_er_diagram(model: type, output_path: Path) -> Path | None:
    """Render an ER SVG for ``model``.

    Returns the path on success, or the previously rendered path if it
    already exists on disk and the new render fails (graphviz ``dot``
    missing, etc.). Returns ``None`` only when no SVG can be exposed.
    """
    try:
        import erdantic
    except ImportError:
        return output_path if output_path.exists() else None
    try:
        diagram = erdantic.create(model)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        diagram.draw(out=str(output_path))
        return output_path
    except Exception:
        return output_path if output_path.exists() else None


# ---------------------------------------------------------------------------
# Type and default formatting
# ---------------------------------------------------------------------------


def _unwrap(annotation: Any) -> Any:
    """Strip Annotated/Optional/Union wrappers and return the inner BaseModel."""
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation
    args = getattr(annotation, "__args__", ()) or ()
    for arg in args:
        if isinstance(arg, type) and issubclass(arg, BaseModel):
            return arg
    return annotation


def _format_default(field: FieldInfo) -> str:
    if field.is_required():
        return "required"
    if field.default_factory is not None:
        return "factory"
    default = field.default
    if isinstance(default, str):
        return f'"{default}"'
    if isinstance(default, Path):
        return f'"{default.as_posix()}"'
    return repr(default)


_TYPE_CLEAN_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"<class '([^']+)'>"), r"\1"),
    (re.compile(r"\bpathlib\._local\."), ""),
    (re.compile(r"\bpathlib\."), ""),
    (re.compile(r"\btyping\."), ""),
    (re.compile(r"\bhydromodpy\."), ""),
    (re.compile(r"\bhmp\."), ""),
    (re.compile(r"\b(?:[\w]+\.)+(?=[A-Z]\w*\b)"), ""),
]


def _strip_annotated(text: str) -> str:
    """Replace ``Annotated[T, ...]`` with ``T`` (recursively) in a type string."""
    keyword = "Annotated["
    while True:
        idx = text.find(keyword)
        if idx == -1:
            return text
        start = idx + len(keyword)
        depth = 0
        first_comma = -1
        close = -1
        i = start
        while i < len(text):
            c = text[i]
            if c == "[":
                depth += 1
            elif c == "]":
                if depth == 0:
                    close = i
                    break
                depth -= 1
            elif c == "," and depth == 0 and first_comma == -1:
                first_comma = i
            i += 1
        if close == -1:
            return text
        first_arg_end = first_comma if first_comma != -1 else close
        first_arg = text[start:first_arg_end].strip()
        text = text[:idx] + first_arg + text[close + 1 :]


def _clean_type_str(text: str) -> str:
    text = _strip_annotated(text)
    for pattern, repl in _TYPE_CLEAN_PATTERNS:
        text = pattern.sub(repl, text)
    return text.strip()


def _format_annotation(field: FieldInfo) -> str:
    annotation = field.annotation
    if isinstance(annotation, type):
        return annotation.__name__
    return _clean_type_str(str(annotation))


def _section_title(name: str) -> str:
    return name.replace("_", " ").title()


# ---------------------------------------------------------------------------
# Description formatting (paragraphs + bullets)
# ---------------------------------------------------------------------------


_BULLET_RE = re.compile(r"^\s*[-*+]\s+")


def _format_description(text: str, indent: str) -> list[str]:
    """Render a Pydantic description preserving paragraphs and bullets.

    Paragraphs are split on blank lines. Within a paragraph, single newlines
    collapse to spaces unless any line starts with a bullet marker.
    """
    text = (text or "").strip()
    if not text:
        return []
    paragraphs = re.split(r"\n[ \t]*\n", text)
    out: list[str] = []
    for index, paragraph in enumerate(paragraphs):
        if index > 0:
            out.append("")
        raw_lines = paragraph.split("\n")
        if any(_BULLET_RE.match(line) for line in raw_lines):
            for line in raw_lines:
                out.append(f"{indent}   {line.rstrip()}" if line.strip() else "")
        else:
            collapsed = " ".join(line.strip() for line in raw_lines if line.strip())
            out.append(f"{indent}   {collapsed}")
    return out


# ---------------------------------------------------------------------------
# Discriminated union detection
# ---------------------------------------------------------------------------


def _get_inner_basemodels(annotation: Any) -> list[type[BaseModel]]:
    """Return every BaseModel reachable inside Optional/Union/list, in order."""
    found: list[type[BaseModel]] = []
    seen_ids: set[int] = set()

    def visit(node: Any) -> None:
        if isinstance(node, type) and issubclass(node, BaseModel):
            if id(node) not in seen_ids:
                seen_ids.add(id(node))
                found.append(node)
            return
        for arg in getattr(node, "__args__", ()) or ():
            visit(arg)

    visit(annotation)
    return found


def _find_discriminator(
    models: list[type[BaseModel]],
) -> tuple[str, dict[type[BaseModel], str]] | None:
    """Detect a tagged-union discriminator across ``models``."""
    if len(models) < 2:
        return None
    common = set(models[0].model_fields.keys())
    for m in models[1:]:
        common &= set(m.model_fields.keys())
    for field_name in sorted(common):
        tags: dict[type[BaseModel], str] = {}
        ok = True
        for model in models:
            f = model.model_fields[field_name]
            if f.is_required() or f.default_factory is not None:
                ok = False
                break
            value = f.default
            if not isinstance(value, str):
                ok = False
                break
            tags[model] = value
        if ok and len(set(tags.values())) == len(models):
            return field_name, tags
    return None


# ---------------------------------------------------------------------------
# Profile, stability, and source-link metadata
# ---------------------------------------------------------------------------


_PROFILE_BADGE_CLASS = {
    Profile.USER: ("bdg-success", "user"),
    Profile.DEV: ("bdg-warning", "dev"),
    Profile.EXPERT: ("bdg-danger", "expert"),
}


def _field_profile(field: FieldInfo) -> Profile:
    return extract_profile(field)


def _field_stability(field: FieldInfo) -> str:
    extra = field.json_schema_extra
    if isinstance(extra, dict):
        value = extra.get("stability") or extra.get("hmp_stability")
        if isinstance(value, str):
            normalized = value.strip().lower()
            if normalized in {"stable", "experimental", "deprecated"}:
                return normalized
    return "stable"


def _class_source_link(model: type[BaseModel]) -> str | None:
    """Return a GitHub permalink to the class declaration line."""
    try:
        source_path = Path(inspect.getfile(model)).resolve()
    except (TypeError, OSError):
        return None
    try:
        relative = source_path.relative_to(REPO_ROOT)
    except ValueError:
        return None
    base = f"https://github.com/{GITHUB_REPO}/blob/{GITHUB_BRANCH}/{relative.as_posix()}"
    try:
        _lines, start = inspect.getsourcelines(model)
    except (OSError, TypeError):
        return base
    return f"{base}#L{start}"


def _field_source_link(model: type[BaseModel], field_name: str) -> str | None:
    """Return a GitHub permalink to the line where ``field_name`` is declared.

    Falls back to the class location if the field cannot be located.
    """
    try:
        source_path = Path(inspect.getfile(model)).resolve()
    except (TypeError, OSError):
        return None
    try:
        relative = source_path.relative_to(REPO_ROOT)
    except ValueError:
        return None
    base = f"https://github.com/{GITHUB_REPO}/blob/{GITHUB_BRANCH}/{relative.as_posix()}"
    try:
        lines, start = inspect.getsourcelines(model)
    except (OSError, TypeError):
        return base
    pattern = re.compile(rf"^\s*{re.escape(field_name)}\s*[:=]")
    for offset, line in enumerate(lines):
        if pattern.match(line):
            return f"{base}#L{start + offset}"
    return f"{base}#L{start}"


# ---------------------------------------------------------------------------
# Field badges and TOML placeholders
# ---------------------------------------------------------------------------


def _field_badges(field: FieldInfo) -> tuple[str, str]:
    type_str = _format_annotation(field)
    default = _format_default(field)
    if default == "required":
        meta = ":bdg-danger:`required`"
    elif default == "factory":
        meta = ":bdg-info:`factory`"
    else:
        meta = f":bdg-secondary:`default = {default}`"
    return type_str, meta


def _stability_badge(stability: str) -> str | None:
    if stability == "stable":
        return None
    if stability == "experimental":
        return ":bdg-warning:`experimental`"
    if stability == "deprecated":
        return ":bdg-danger:`deprecated`"
    return None


def _profile_badge(profile: Profile) -> str:
    badge_class, label = _PROFILE_BADGE_CLASS[profile]
    return f":{badge_class}:`{label}`"


def _toml_placeholder(field: FieldInfo) -> str:
    """Return one TOML-valid placeholder for ``field``.

    Used by Couche 4 to keep copy-paste blocks parseable. Required and
    factory fields are emitted as commented-out lines.
    """
    annotation_str = _format_annotation(field).lower()
    if "bool" in annotation_str:
        return "false"
    if "int" in annotation_str:
        return "0"
    if "float" in annotation_str:
        return "0.0"
    if "list" in annotation_str:
        return "[]"
    if "dict" in annotation_str:
        return "{}"
    return '""'


# ---------------------------------------------------------------------------
# Field rendering
# ---------------------------------------------------------------------------


_ANCHOR_INVALID = re.compile(r"[^a-z0-9-]+")


def _anchor_id(*parts: str) -> str:
    raw = "-".join(part.replace(".", "-").replace("_", "-") for part in parts if part)
    cleaned = _ANCHOR_INVALID.sub("-", raw.lower()).strip("-")
    return re.sub(r"-+", "-", cleaned)


def _toml_path(*parts: str) -> str:
    return ".".join(part for part in parts if part)


def _toml_usage(field: FieldInfo, full_path: str) -> str:
    """Return how ``full_path`` is meant to appear in a TOML file.

    - ``[[full_path]]`` for ``list[BaseModel]``
    - ``[full_path.<id>]`` for ``dict[str, ...]``
    - ``[full_path]`` for ``BaseModel``
    - ``full_path = ...`` for scalars
    """
    annotation = field.annotation
    inner_models = _get_inner_basemodels(annotation)
    annotation_str = _format_annotation(field).lower()
    if "list[" in annotation_str and inner_models:
        return f"[[{full_path}]]"
    if "dict[" in annotation_str:
        return f"[{full_path}.<id>]"
    if inner_models:
        return f"[{full_path}]"
    return f"{full_path} = ..."


def _render_field_block(
    field_name: str,
    field: FieldInfo,
    *,
    model: type[BaseModel],
    section_path: str,
    depth: int,
    indent: str,
    seen: set[int],
    anchor_namespace: str = "",
) -> list[str]:
    """Render one Pydantic field with a wrapper carrying anchor + level class."""
    type_str, badge = _field_badges(field)
    profile = _field_profile(field)
    stability = _field_stability(field)
    source_link = _field_source_link(model, field_name)

    inner_models = _get_inner_basemodels(field.annotation)
    discriminator = _find_discriminator(inner_models) if len(inner_models) > 1 else None
    annotation_str = _format_annotation(field).lower()
    dynamic_key = "<id>" if "dict[" in annotation_str else ""

    full_path = _toml_path(section_path, field_name)
    anchor = _anchor_id(anchor_namespace, full_path) if anchor_namespace else _anchor_id(full_path)
    level_class = _PROFILE_BADGE_CLASS[profile][1]

    if discriminator is not None:
        disc_name, disc_tags = discriminator
        choices = " | ".join(f'"{tag}"' for tag in disc_tags.values())
        type_badge = f":bdg-primary:`{disc_name} = {choices}`"
    else:
        type_badge = f":bdg-primary:`{type_str}`"

    toml_usage = _toml_usage(field, full_path)
    inner = indent + "   "
    lines: list[str] = [
        f"{indent}.. container:: hmp-field hmp-field-level-{level_class}",
        f"{indent}   :name: {anchor}",
        "",
        f"{inner}.. raw:: html",
        "",
        f'{inner}   <div class="hmp-field-header" data-toml-path="{html.escape(full_path, quote=True)}">',
        f'{inner}     <code class="hmp-field-name">{html.escape(field_name)}</code>',
        f'{inner}     <span class="hmp-field-arrow">in TOML:</span>',
        f'{inner}     <code class="hmp-field-toml">{html.escape(toml_usage)}</code>',
        f"{inner}   </div>",
        "",
    ]
    badge_parts = [type_badge, badge, _profile_badge(profile)]
    stability_part = _stability_badge(stability)
    if stability_part is not None:
        badge_parts.append(stability_part)
    if source_link is not None:
        badge_parts.append(f"`source <{source_link}>`__")
    lines.append(f"{inner}{' '.join(badge_parts)}")
    lines.append("")

    description_lines = _format_description(field.description or "", inner)
    if description_lines:
        lines.extend(description_lines)
        lines.append("")
    if discriminator is not None:
        disc_name, _ = discriminator
        lines.append(
            f"{inner}   Set ``{disc_name}`` in your TOML to choose one of the schemas below."
        )
        lines.append("")

    if depth < MAX_NESTED_DEPTH:
        for inner_model in inner_models:
            if id(inner_model) in seen:
                continue
            nested_seen = seen | {id(inner_model)}
            if discriminator is not None:
                disc_name, disc_tags = discriminator
                tag = disc_tags[inner_model]
                title = f'``{disc_name} = "{tag}"``  ({inner_model.__name__})'
                hidden_field = disc_name
                nested_path = _toml_path(full_path, tag, dynamic_key)
                child_namespace = anchor_namespace
            else:
                title = f"Fields of ``{inner_model.__name__}``"
                hidden_field = None
                nested_path = _toml_path(full_path, dynamic_key)
                if len(inner_models) > 1:
                    sub_namespace = inner_model.__name__.lower()
                    child_namespace = (
                        f"{anchor_namespace}-{sub_namespace}" if anchor_namespace else sub_namespace
                    )
                else:
                    child_namespace = anchor_namespace
            lines.extend(
                [
                    f"{inner}.. dropdown:: {title}",
                    f"{inner}   :icon: list-unordered",
                    f"{inner}   :animate: fade-in-slide-down",
                    "",
                    f"{inner}   .. rst-class:: hmp-config-fields hmp-config-fields-nested",
                    "",
                ]
            )
            sub_indent = inner + "   "
            for sub_name, sub_field in inner_model.model_fields.items():
                if getattr(sub_field, "exclude", False):
                    continue
                if hidden_field is not None and sub_name == hidden_field:
                    continue
                lines.extend(
                    _render_field_block(
                        sub_name,
                        sub_field,
                        model=inner_model,
                        section_path=nested_path,
                        depth=depth + 1,
                        indent=sub_indent,
                        seen=nested_seen,
                        anchor_namespace=child_namespace,
                    )
                )
            lines.append("")
    elif inner_models:
        lines.append(
            f"{inner}*Nested structure truncated at depth {MAX_NESTED_DEPTH}. "
            f"See :doc:`config_index` for the complete TOML path listing.*"
        )
        lines.append("")

    lines.append("")
    return lines


# ---------------------------------------------------------------------------
# TOML starter snippet (auto-derived from USER-profile defaults)
# ---------------------------------------------------------------------------


def _render_starter_snippet(section_name: str, model: type[BaseModel]) -> list[str]:
    """Return a minimal TOML starter for ``[section_name]`` (USER fields only).

    Top-level scalars first, then nested ``BaseModel`` and list[BaseModel]
    fields rendered as ``[parent.subfield]`` / ``[[parent.subfield]]``
    sub-tables so the user sees the full TOML shape, not just the leaves.
    """
    lines = [f"[{section_name}]"]
    nested_subtables: list[tuple[str, type[BaseModel]]] = []

    for field_name, field in model.model_fields.items():
        if getattr(field, "exclude", False):
            continue
        if _field_profile(field) is not Profile.USER:
            continue
        inner_models = _get_inner_basemodels(field.annotation)
        annotation_str = _format_annotation(field).lower()
        if "list[" in annotation_str and inner_models:
            nested_subtables.append((f"[[{section_name}.{field_name}]]", inner_models[0]))
            continue
        if "dict[" in annotation_str:
            lines.append(f"# [{section_name}.{field_name}.<id>]")
            continue
        if inner_models:
            nested_subtables.append((f"[{section_name}.{field_name}]", inner_models[0]))
            continue
        if field.is_required():
            lines.append(f"# {field_name} = {_toml_placeholder(field)}  # REQUIRED")
            continue
        if field.default_factory is not None:
            lines.append(f"# {field_name} = ...  # uses factory default")
            continue
        default = field.default
        if isinstance(default, str):
            lines.append(f'# {field_name} = "{default}"')
        elif isinstance(default, bool):
            lines.append(f"# {field_name} = {'true' if default else 'false'}")
        elif isinstance(default, Path):
            lines.append(f'# {field_name} = "{default.as_posix()}"')
        elif default is None:
            lines.append(f"# {field_name} = ...  # default = None")
        else:
            lines.append(f"# {field_name} = {default!r}")

    for header, sub_model in nested_subtables:
        lines.append("")
        lines.append(header)
        for sub_name, sub_field in sub_model.model_fields.items():
            if getattr(sub_field, "exclude", False):
                continue
            if _field_profile(sub_field) is not Profile.USER:
                continue
            if sub_field.is_required():
                lines.append(f"# {sub_name} = {_toml_placeholder(sub_field)}  # REQUIRED")
            elif sub_field.default_factory is not None:
                lines.append(f"# {sub_name} = ...  # factory default")
            else:
                default = sub_field.default
                if isinstance(default, str):
                    lines.append(f'# {sub_name} = "{default}"')
                elif isinstance(default, bool):
                    lines.append(f"# {sub_name} = {'true' if default else 'false'}")
                elif isinstance(default, Path):
                    lines.append(f'# {sub_name} = "{default.as_posix()}"')
                elif default is None:
                    lines.append(f"# {sub_name} = ...  # default = None")
                else:
                    lines.append(f"# {sub_name} = {default!r}")
    return lines


# ---------------------------------------------------------------------------
# Couche 1: overview (cards + toctree)
# ---------------------------------------------------------------------------


def _render_couche1(top_fields: dict[str, FieldInfo]) -> str:
    lines = [
        GENERATED_HEADER,
        "Configuration overview",
        "======================",
        "",
        "Card-based map of every TOML section validated by ``HydroModPyConfig``.",
        "Click a card to open the section detail page.",
        "",
        "**Companion pages**",
        "",
        "- :doc:`config_index` -- flat global index, Ctrl+F friendly",
        "- :doc:`complete_toml` -- full annotated TOML reference",
        "- :doc:`schema_explorer` -- interactive JSON Schema viewer",
        "- :doc:`recipes` -- task-oriented cookbook",
        "- :doc:`validate` -- pre-flight your project.toml in the browser",
        "",
        "Quick search across every TOML path",
        "-----------------------------------",
        "",
        ".. raw:: html",
        "",
        '   <div class="hmp-config-search">',
        '     <input type="search" id="hmp-config-search-input" '
        'placeholder="Search any field, section, or TOML path..."'
        ' autocomplete="off" />',
        '     <div id="hmp-config-search-results" class="hmp-config-search-results"></div>',
        "   </div>",
        "",
        "Sections",
        "--------",
        "",
        ".. grid:: 1 1 2 3",
        "   :gutter: 2 2 3 3",
        "",
    ]
    for name, field in top_fields.items():
        model = _unwrap(field.annotation)
        if not (isinstance(model, type) and issubclass(model, BaseModel)):
            continue
        description = (field.description or "").replace("\n", " ").strip()
        lines.extend(
            [
                "   .. grid-item-card::",
                f"      :link: {name}",
                "      :link-type: doc",
                "      :class-card: sd-shadow-sm sd-rounded-3 sd-p-3",
                "",
                f"      **[{name}]**",
                "      ^^^",
                f"      {description or _section_title(name)}",
                "",
            ]
        )
    lines.extend(
        [
            ".. toctree::",
            "   :hidden:",
            "",
            "   config_index",
            "   complete_toml",
            "   schema_explorer",
            "   recipes",
            "   validate",
        ]
    )
    for name, field in top_fields.items():
        model = _unwrap(field.annotation)
        if isinstance(model, type) and issubclass(model, BaseModel):
            lines.append(f"   {name}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Couche 2: per-section page
# ---------------------------------------------------------------------------


def _render_couche2(
    section_name: str,
    model: type[BaseModel],
    diagram_rel: str | None,
    gallery_cases: list[tuple[str, str]] | None = None,
) -> str:
    title = f"[{section_name}] {model.__name__}"
    source_link = _class_source_link(model)
    lines = [
        GENERATED_HEADER,
        f"{title}",
        "=" * len(title),
        "",
        ".. contents:: On this page",
        "   :local:",
        "   :depth: 2",
        "",
        f"TOML section: ``[{section_name}]``",
        "",
        f"Pydantic model: ``{model.__name__}`` defined in ``{model.__module__}``.",
    ]
    if source_link:
        lines.append("")
        lines.append(f"`Source on GitHub <{source_link}>`__")
    lines.append("")

    docstring = (model.__doc__ or "").strip()
    if docstring:
        lines.extend([docstring, ""])

    lines.extend(_render_level_toggle(section_name))

    lines.extend(
        [
            "Fields",
            "------",
            "",
            ".. rst-class:: hmp-config-fields",
            "",
        ]
    )
    seen_models = {id(model)}
    for field_name, field in model.model_fields.items():
        if getattr(field, "exclude", False):
            continue
        lines.extend(
            _render_field_block(
                field_name,
                field,
                model=model,
                section_path=section_name,
                depth=0,
                indent="",
                seen=seen_models,
            )
        )

    lines.extend(_render_starter_snippet_dropdown(section_name, model))

    if gallery_cases:
        lines.extend(
            [
                "Cases using this section",
                "------------------------",
                "",
                "Validation gallery cases that reference fields from this section:",
                "",
            ]
        )
        for slug, _title in gallery_cases:
            lines.append(f"- :doc:`/{GALLERY_CASES_DIR}/{slug}`")
        lines.append("")

    if diagram_rel:
        lines.extend(
            [
                "Entity-relationship diagram",
                "---------------------------",
                "",
                ".. container:: hmp-er-wrapper",
                "",
                f"   .. image:: {diagram_rel}",
                f"      :alt: ER diagram for {model.__name__}",
                "      :class: er-diagram hmp-zoomable",
                f"      :target: {diagram_rel}",
                "",
                "   .. container:: hmp-er-hint",
                "",
                "      Click to zoom and pan. Press *Esc* or click outside to close.",
                "",
            ]
        )

    return "\n".join(lines)


def _render_starter_snippet_dropdown(section_name: str, model: type[BaseModel]) -> list[str]:
    """Render the TOML starter snippet as a collapsible dropdown."""
    lines = [
        "Starter TOML snippet",
        "--------------------",
        "",
        f".. dropdown:: Click to expand a copy-pasteable ``[{section_name}]`` TOML skeleton",
        "   :icon: code",
        "   :animate: fade-in-slide-down",
        "",
        "   Copy this block into your ``project.toml`` and uncomment the lines",
        "   you want to set. Sub-tables (``[parent.subfield]``) appear in the",
        "   order Pydantic expects them.",
        "",
        "   .. code-block:: toml",
        "",
    ]
    for snippet_line in _render_starter_snippet(section_name, model):
        lines.append(f"      {snippet_line}" if snippet_line else "")
    lines.append("")
    return lines


def _render_level_toggle(section_name: str) -> list[str]:
    """Render the per-section Common/Dev/Expert visibility toggle."""
    return [
        ".. raw:: html",
        "",
        f'   <div class="hmp-level-toggle" data-section="{section_name}">',
        '     <span class="hmp-level-toggle-label">Show fields:</span>',
        '     <button type="button" data-level="user" class="hmp-level-btn is-active">'
        "User</button>",
        '     <button type="button" data-level="dev" class="hmp-level-btn">User + Dev</button>',
        '     <button type="button" data-level="expert" class="hmp-level-btn">All</button>',
        "   </div>",
        "",
    ]


# ---------------------------------------------------------------------------
# Couche 3: schema explorer (Stoplight)
# ---------------------------------------------------------------------------


def _render_couche3() -> str:
    lines = [
        GENERATED_HEADER,
        "Schema Explorer",
        "===============",
        "",
        "This page renders the canonical JSON Schema of ``HydroModPyConfig`` with",
        "the Stoplight Elements viewer. The same schema is downloadable as a",
        "single artifact for use in editors, CI validators, or API tooling that",
        "consumes JSON Schema directly.",
        "",
        "Download: :download:`hydromodpy-schema.json </_static/hydromodpy-schema.json>`",
        "",
        ".. note::",
        "   The viewer loads the Stoplight Elements bundle from the unpkg CDN at",
        "   runtime. If the CDN is unreachable, the page still works as a typed",
        "   download link plus the structured cards on :doc:`index`.",
        "",
        ".. raw:: html",
        "",
        '   <link rel="stylesheet" href="https://unpkg.com/@stoplight/elements/styles.min.css">',
        '   <script src="https://unpkg.com/@stoplight/elements/web-components.min.js"'
        ' type="module"></script>',
        '   <div class="hmp-schema-explorer">',
        "     <elements-api",
        '       apiDescriptionUrl="../../_static/hydromodpy-schema.json"',
        '       router="hash"',
        '       layout="sidebar"',
        '       hideExport="true">',
        "     </elements-api>",
        "   </div>",
        "",
        "See Also",
        "--------",
        "",
        "- :doc:`index` for the layered cards",
        "- :doc:`complete_toml` for the annotated TOML reference",
        "- :doc:`config_index` for the flat global index",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Couche 4: complete TOML reference (now valid TOML)
# ---------------------------------------------------------------------------


def _render_couche4(top_fields: dict[str, FieldInfo]) -> str:
    lines = [
        GENERATED_HEADER,
        "Complete annotated TOML reference",
        "=================================",
        "",
        "Every TOML section with its direct fields, defaults and types.",
        "Sub-models are linked back to their per-section page.",
        "",
        ".. tip::",
        "   The blocks below produce **valid TOML** when copy-pasted.",
        "   Required and factory fields are commented out: uncomment and",
        "   replace the placeholder before running the project.",
        "",
    ]
    for name, field in top_fields.items():
        model = _unwrap(field.annotation)
        if not (isinstance(model, type) and issubclass(model, BaseModel)):
            continue
        lines.append(f".. dropdown:: ``[{name}]`` ({model.__name__})")
        lines.append("   :icon: gear")
        lines.append("")
        lines.append(f"   See :doc:`{name}` for the full description.")
        lines.append("")
        lines.append("   .. code-block:: toml")
        lines.append("")
        lines.append(f"      [{name}]")
        for field_name, sub_field in model.model_fields.items():
            if getattr(sub_field, "exclude", False):
                continue
            description = (sub_field.description or "no description").replace("\n", " ").strip()
            lines.append(f"      # {description}")
            if sub_field.is_required():
                placeholder = _toml_placeholder(sub_field)
                lines.append(f"      # {field_name} = {placeholder}  # REQUIRED")
            elif sub_field.default_factory is not None:
                lines.append(f"      # {field_name} = ...  # uses factory default")
            else:
                default = sub_field.default
                if isinstance(default, str):
                    lines.append(f'      {field_name} = "{default}"')
                elif isinstance(default, bool):
                    lines.append(f"      {field_name} = {'true' if default else 'false'}")
                elif isinstance(default, Path):
                    lines.append(f'      {field_name} = "{default.as_posix()}"')
                elif default is None:
                    lines.append(f"      # {field_name} = ...  # default = None")
                else:
                    lines.append(f"      {field_name} = {default!r}")
        lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Couche 5: flat global index
# ---------------------------------------------------------------------------


def _walk_field_paths(
    model: type[BaseModel],
    section_path: str,
    *,
    depth: int = 0,
    seen: set[int] | None = None,
) -> list[tuple[str, str, str, str | None, str | None]]:
    """Return tuples (toml_path, type, profile, stability, source_url)."""
    if seen is None:
        seen = {id(model)}
    out: list[tuple[str, str, str, str | None, str | None]] = []
    for field_name, field in model.model_fields.items():
        if getattr(field, "exclude", False):
            continue
        full_path = _toml_path(section_path, field_name)
        type_str = _format_annotation(field)
        profile = _field_profile(field).name.lower()
        stability = _field_stability(field)
        source = _field_source_link(model, field_name)
        out.append((full_path, type_str, profile, stability, source))
        if depth < MAX_NESTED_DEPTH:
            inner_models = _get_inner_basemodels(field.annotation)
            discriminator = _find_discriminator(inner_models) if len(inner_models) > 1 else None
            annotation_str = _format_annotation(field).lower()
            dynamic_key = "<id>" if "dict[" in annotation_str else ""
            for inner in inner_models:
                if id(inner) in seen:
                    continue
                if discriminator is not None:
                    disc_name, disc_tags = discriminator
                    nested_path = _toml_path(full_path, disc_tags[inner], dynamic_key)
                else:
                    nested_path = _toml_path(full_path, dynamic_key)
                out.extend(
                    _walk_field_paths(
                        inner,
                        nested_path,
                        depth=depth + 1,
                        seen=seen | {id(inner)},
                    )
                )
    return out


def _render_couche5(top_fields: dict[str, FieldInfo]) -> str:
    lines = [
        GENERATED_HEADER,
        "Configuration index",
        "===================",
        "",
        "Flat list of every TOML path validated by ``HydroModPyConfig``.",
        "Use Ctrl+F to jump to a specific path. Each row links back to the",
        "per-section page (anchor) and to the source declaration on GitHub.",
        "",
        ".. list-table::",
        "   :header-rows: 1",
        "   :widths: 35 25 10 10 10 10",
        "   :class: hmp-config-index",
        "",
        "   * - TOML path",
        "     - Type",
        "     - Profile",
        "     - Stability",
        "     - Page",
        "     - Source",
    ]
    for name, field in top_fields.items():
        model = _unwrap(field.annotation)
        if not (isinstance(model, type) and issubclass(model, BaseModel)):
            continue
        for full_path, type_str, profile, stability, source in _walk_field_paths(model, name):
            anchor = _anchor_id(full_path)
            page_link = f"`{name} <{name}.html#{anchor}>`__"
            source_cell = f"`link <{source}>`__" if source else "-"
            stability_cell = stability if stability != "stable" else "-"
            lines.extend(
                [
                    f"   * - ``{full_path}``",
                    f"     - ``{type_str}``",
                    f"     - {profile}",
                    f"     - {stability_cell}",
                    f"     - {page_link}",
                    f"     - {source_cell}",
                ]
            )
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Schema export
# ---------------------------------------------------------------------------


def export_schema(output_path: Path | None = None) -> Path:
    """Write the canonical JSON Schema to ``_static/hydromodpy-schema.json``."""
    target = (output_path or SCHEMA_OUTPUT).resolve()
    target.parent.mkdir(parents=True, exist_ok=True)
    schema = HydroModPyConfig.model_json_schema()
    target.write_text(json.dumps(schema, indent=2, sort_keys=False) + "\n")
    return target


def export_search_index(top_fields: dict[str, FieldInfo], output_path: Path | None = None) -> Path:
    """Write a flat JSON index used by the in-page Ctrl+F search widget."""
    entries: list[dict[str, str]] = []
    for name, field in top_fields.items():
        model = _unwrap(field.annotation)
        if not (isinstance(model, type) and issubclass(model, BaseModel)):
            continue
        for full_path, type_str, profile, stability, source in _walk_field_paths(model, name):
            anchor = _anchor_id(full_path)
            field_name = full_path.rsplit(".", 1)[-1]
            field_info = _field_info_for_path(model, full_path[len(name) + 1 :])
            description = ""
            if field_info is not None and field_info.description:
                description = field_info.description.replace("\n", " ").strip()[:240]
            entries.append(
                {
                    "path": full_path,
                    "name": field_name,
                    "type": type_str,
                    "profile": profile,
                    "stability": stability,
                    "section": name,
                    "anchor": anchor,
                    "page": f"{name}.html",
                    "source": source or "",
                    "description": description,
                }
            )
    target = (output_path or SEARCH_INDEX_OUTPUT).resolve()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(entries, indent=2, sort_keys=False) + "\n")
    return target


def _field_info_for_path(model: type[BaseModel], dotted: str) -> FieldInfo | None:
    """Drill into ``model`` along ``dotted`` (skipping unknown segments)."""
    if not dotted:
        return None
    current_model: type[BaseModel] | None = model
    info: FieldInfo | None = None
    for segment in dotted.split("."):
        if current_model is None:
            return None
        info = current_model.model_fields.get(segment)
        if info is None:
            return None
        inner = _get_inner_basemodels(info.annotation)
        current_model = inner[0] if inner else None
    return info


# ---------------------------------------------------------------------------
# Top-level entry point
# ---------------------------------------------------------------------------


def generate_all(output_dir: Path | None = None) -> list[Path]:
    """Render every generated RST file. Returns the paths that were written."""
    with contextlib.chdir(REPO_ROOT):
        return _generate_all_impl(output_dir)


def _generate_all_impl(output_dir: Path | None) -> list[Path]:
    out = (output_dir or REFERENCE_DIR).resolve()
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    _report_uncovered_opaque_fields()

    top_fields = HydroModPyConfig.model_fields

    index_path = out / "index.rst"
    index_path.write_text(_render_couche1(top_fields))
    written.append(index_path)

    schema_path = export_schema()
    written.append(schema_path)
    explorer_path = out / "schema_explorer.rst"
    explorer_path.write_text(_render_couche3())
    written.append(explorer_path)

    complete_path = out / "complete_toml.rst"
    complete_path.write_text(_render_couche4(top_fields))
    written.append(complete_path)

    config_index_path = out / "config_index.rst"
    config_index_path.write_text(_render_couche5(top_fields))
    written.append(config_index_path)

    search_index_path = export_search_index(top_fields)
    written.append(search_index_path)

    validate_path = out / "validate.rst"
    validate_path.write_text(_render_validate_page())
    written.append(validate_path)

    diagram_root = out / "_diagrams"
    diagram_root.mkdir(parents=True, exist_ok=True)
    section_cases = _scan_section_to_cases()

    for name, field in top_fields.items():
        model = _unwrap(field.annotation)
        if not (isinstance(model, type) and issubclass(model, BaseModel)):
            continue
        diagram_rel: str | None = None
        diagram_path = diagram_root / f"{name}.svg"
        rendered = _try_render_er_diagram(model, diagram_path)
        if rendered is not None:
            diagram_rel = f"_diagrams/{name}.svg"
            written.append(rendered)
        page_path = out / f"{name}.rst"
        page_path.write_text(_render_couche2(name, model, diagram_rel, section_cases.get(name, [])))
        written.append(page_path)

    return written


def _render_validate_page() -> str:
    lines = [
        GENERATED_HEADER,
        "Validate your project.toml",
        "==========================",
        "",
        "HydroModPy validates configuration through Pydantic v2. There are",
        "three ways to validate a ``project.toml`` before launching a long",
        "run:",
        "",
        "1. **CLI**: ``hmp validate path/to/project.toml`` (recommended).",
        "2. **Python**: load and validate explicitly:",
        "",
        ".. code-block:: python",
        "   :class: no-codeautolink",
        "",
        "   from hydromodpy.config import HydroModPyConfig",
        "   import tomllib",
        "",
        "   with open('project.toml', 'rb') as fh:",
        "       payload = tomllib.load(fh)",
        "   HydroModPyConfig.model_validate(payload)",
        "",
        "3. **Browser**: paste a TOML payload below to run a structural",
        "   pre-flight against the JSON Schema. This is approximate; the",
        "   Python validator remains authoritative.",
        "",
        ".. raw:: html",
        "",
        '   <div class="hmp-validate-widget">',
        '     <textarea id="hmp-validate-input" rows="18" '
        'placeholder="workflow = &quot;simulation&quot;&#10;&#10;[workspace]&#10;'
        'project_root = &quot;.&quot;&#10;&#10;# paste the rest of your TOML here..."'
        "></textarea>",
        '     <div class="hmp-validate-actions">',
        '       <button type="button" id="hmp-validate-run">Validate structure</button>',
        '       <button type="button" id="hmp-validate-clear">Clear</button>',
        "     </div>",
        '     <pre id="hmp-validate-output" class="hmp-validate-output"></pre>',
        "   </div>",
        "",
        "Schema and CLI",
        "--------------",
        "",
        "- :download:`hydromodpy-schema.json </_static/hydromodpy-schema.json>`",
        "- See also :doc:`schema_explorer` for the interactive viewer",
        "- ``hmp install-binaries`` if MODFLOW binaries are missing on first run",
        "",
    ]
    return "\n".join(lines)


def _report_uncovered_opaque_fields() -> None:
    """Emit a clear warning when an opaque dict[...] field remains in the schema."""
    try:
        uncovered = find_uncovered_opaque_fields(HydroModPyConfig)
    except Exception as exc:
        print(f"[doc_config] coverage check skipped: {exc}")
        return
    if not uncovered:
        return
    print("[doc_config] WARNING: uncovered opaque TOML paths detected:")
    for entry in uncovered:
        print(f"  - {entry.toml_path}  ({entry.annotation})")
    print(
        "[doc_config] Replace each opaque payload with a typed BaseModel or add a "
        "free-form mapping to INTENTIONALLY_OPAQUE_PATHS."
    )


__all__ = ["generate_all", "export_schema", "export_search_index"]
